### ISSUE TITLE
NPP opens with a Blank Session, after Win10 Automatic Restart following Update

### ISSUE THREAD

**Issue by swift1978** [notepad-plus-plus/notepad-plus-plus#10402]
### Description of the Issue
NPP opens with a Blank Session, after Win10 Automatic Restart following Update.

It is very difficult to stop Win 10 from restarting by itself following an Update, during Inactive hours. The Internet is full of people searching on tips to avoid that.

What happens with NPP is that (it doesn't happen every time, but about once in 3 times), it does not safely save and close the Session.xml file.

I believe that when NPP is re-launched, it finds the Session.xml file corrupted, and over-writes it with a Blank Session file, and opens in a Blank Session.

It becomes a nag, because we have so many text files we are working on, arranged in a particular order, and working between them, as a Writer.
It's very difficult to recall which files were open and in which order, and then to get back to a semblance of where we where, we have to spend nearly half a day till we are somewhere comfortable again.

I had reported on this earlier, along with a Null file issue I had with unsaved files.

I had suggested for NPP to look at having a set of Time-stamped Session files, say about the latest 10 at all times, at whatever time interval you'll feel optimal.
At every new save, the oldest one would be removed.

So, for whatever reason, NPP crashes, or is force-closed before it can save and exit properly, which causes the Session.xml file to get corrupt.

NPP at next re-launch could check the integrity of the Session.xml file, attempt repair, and if not possible, load with the previous Session.xml file, and alert the user that this has happened and it has taken this action...

I am sure users would bless you for this, and feel so so much more secure using NPP.

Thanks a load for your wonderful program, and for all your support. 

### Debug Information
Notepad++ v8.1.2   (64-bit)
Build time : Jul 16 2021 - 01:59:50
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 2009
OS Build : 19042.985
Current ANSI codepage : 1252
Plugins : AutoSave.dll ComparePlugin.dll mimeTools.dll NppConverter.dll NppExport.dll SessionMgr.dll

**Comment by ArkadiuszMichalski** [comment]
It looks like https://github.com/notepad-plus-plus/notepad-plus-plus/commit/62efa463b0a74426af0f3f6ed10382b52a4ac799 did not fix it (or not all cases).

**Comment by donho** [comment]
@pnedev 
Could this issue be fixed by https://github.com/notepad-plus-plus/notepad-plus-plus/commit/9aa9ecb664bd03f3a61cc42891f125492767e066 ?

**Comment by pnedev** [comment]
> @pnedev Could this issue be fixed by [9aa9ecb](https://github.com/notepad-plus-plus/notepad-plus-plus/commit/9aa9ecb664bd03f3a61cc42891f125492767e066) ?
> 
> _**edit: After checking tinyxml code, I'm quite sure this issue persists after your fix. I'll try to integrate your CFile into TinyXML.**_

@donho,

You are right - https://github.com/notepad-plus-plus/notepad-plus-plus/commit/9aa9ecb664bd03f3a61cc42891f125492767e066 doesn't fix this bug but provides the means to do so.
Since session files are xml they are written by TinyXML library and it still uses the old C type file write functions.
You'll need to change the TinyXML code to use the new CFile API from https://github.com/notepad-plus-plus/notepad-plus-plus/commit/9aa9ecb664bd03f3a61cc42891f125492767e066 to write the config/session xml files.

**Comment by donho** [comment]
@pnedev 
Done in https://github.com/notepad-plus-plus/notepad-plus-plus/pull/10612
You're welcome to review the code if you want.

**Comment by pnedev** [comment]
@donho ,

I actually commented already but here: https://github.com/donho/notepad-plus-plus/commit/a8ec068965b2a0eed010b53d88a18d14bb678e58#commitcomment-57345690

**Comment by donho** [comment]
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/6133#issuecomment-968270646

**Comment by donho** [comment]
Fix by https://github.com/notepad-plus-plus/notepad-plus-plus/commit/6000f3bb21a42a4d28d068617e0dc642ef739b26
