### ISSUE TITLE
Function List inactive highlight not visible in dark themes

### ISSUE THREAD

**Issue by vinsworldcom** [notepad-plus-plus/notepad-plus-plus#10792]
### Description of the Issue
Not using Dark Mode, just a dark theme (Obsidian), the Function List highlight, when inactive (i.e., typing in the editor window) is no longer (easily) visible to the casual glance.  It seems the text is bolded for the current function, but the background highlighting - if any - is not visible.  This change after version 8.1.2.

8.1.2 (clearly visible):
![image](https://user-images.githubusercontent.com/9657169/142128372-abf5b143-0c9a-4a6b-9374-2d19125fcad8.png)

8.1.9.1 (barely noticeable):
![image](https://user-images.githubusercontent.com/9657169/142128423-a5aaa3ba-66fe-4e3c-9604-3f7749632f00.png)

8.1.9.1 (using regular theme - easily visible):
![image](https://user-images.githubusercontent.com/9657169/142128514-19a0239e-d281-481b-b2d7-d8e904698439.png)

Also see [old discussion at the Community](https://community.notepad-plus-plus.org/topic/19071/function-list-current-function-highlighting-is-too-light?_=1637117937219).

### Steps to Reproduce the Issue

As seen above, use a dark theme (e.g., Obsidian in any N++ version greater than 8.1.2 and the current Function List function inactive highlight is barely visible (second image above).

Switch to the default theme and it is clearly visible (third image above).

### Expected Behavior
I would like to have the background highlighting of the current function in Function List be more visible when the list is inactive (i.e., editing in the text window).  Could this possibly be a "Global Style" which can be configured?  Not sure if it will be set in:

- notepad-plus-plus\PowerEditor\src\WinControls\FunctionList\functionListPanel.cpp
- notepad-plus-plus\PowerEditor\src\WinControls\TreeView\TreeView.cpp

### Debug Information
Notepad++ v8.1.9.1   (64-bit)
Build time : Nov 15 2021 - 23:20:55
Path : C:\usr\bin\npp64\notepad++.exe
Command Line : .\tmp\ifconfig\ifconfig.c
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2009
OS Build : 19042.1348
Current ANSI codepage : 1252
Plugins :

**Comment by thomassmith311** [comment]
Only happens in some dark themes - in my judgment it is hard to see on
- DansLeRuSH-Dark
- Monokai
- Obsidian
Some other themes that I think are kind of hard to see but not too bad:
- DarkModeDefault / Zenburn
- Mono Industrial
I searched the XML file for Obsidian and used GIMP to find the Hex code for the highlight color. The highlighted color is `#333333`, while the unhighlighted background of the side windows is `#293134`. 293134 appears all over the XML, but 333333 does not, which makes me think that 333333 might be generated automatically somehow or else is independent of the XML.

**Comment by thomassmith311** [comment]
Okay, I discovered something interesting:
The styles Choco, DarkModeDefault/Zenburn, Bespin, Black board, DansLeRuSH Dark, Deep black, HotFudgeSundae, MonoIndustrial, Monokai, Mossy Lawn, Obsidian, Plastic Code Wrap, Ruby Blue, Solarized, Twilight, Vibrant Ink, and vim Dark Blue all have `#333333` as the highlight color. However, I still can't find that value anywhere in the XML files.

**Comment by vinsworldcom** [comment]
@thomassmith311 pretty sure N++ is now pulling that highlight color from Windows as there is not a N++ style config for that highlight color.  That's what I'm hoping this issue will resolve - a Style Configurator style for highlight.

You can verify by opening Windows Explorer, highlighting a folder in the left pane and then clicking in the right pane.  The folder highlight is #333333:

![image](https://user-images.githubusercontent.com/9657169/143295735-84ff24ed-2aae-4782-9592-389b35fe81ae.png)

Cheers.

**Comment by thomassmith311** [comment]
@vinsworldcom Okay, that's interesting. But, I wonder why some themes (e.g., Hello Kitty) use a different color.

**Comment by vinsworldcom** [comment]
@thomassmith311 hmm... interesting.  I wonder if maybe the highlight is an "alpha" color meaning it is a transparent color - like grey but transparent so when combined with the underlying background in "Hello Kitty" - hot pink - puts a pink hue on an otherwise rather grey-looking highlight.

Cheers.

**Comment by Docteh** [comment]
Messing with the Hello Kitty style, looks like the "Default Style" is what controls the background, and it does look like the highlight color is merely the background color darkened

**Comment by ozone10** [comment]
Should be fixed.

**Comment by sXNA** [comment]
Cannot reproduce in latest notepad++ 8.4.9

**Comment by DavidOgilvie** [comment]
I still can't see the highlight in the autocomplete menu, even though I just installed NP++ 8.5.  I would suggest that the software use the highlight color of the current text line.  That can at least be set to our preference, and it should work well for the context menu as well.

**Comment by jabcreations** [comment]
As of November 13th 2023 this is still an issue. I've been using the Obsidian theme for years and yesterday decided to make it an actual dark mode theme. I've gone through all of the global style background-colors and nothing has any effect. I've gone through the `Notepad++\functionList\php.xml` and `Notepad++\themes\Obsidian.xml` files and couldn't distinguish anything relevant. The Find modal window's count is still blue which has terrible contrast and is another theme option that needs to be fixed. These are the only two issues I have with Notepad++ right now.  I work with interpreted languages not compiled languages so I'm not sure where to search through the code (not do I have any time to do so unfortunately).

**Comment by jabcreations** [comment]
So this was getting irritating and I reread earlier comments. I experimented and came up with a temporarily acceptable solution:

Using the Obsidian theme:

1. For the Global Styles choose 'Default Style'.
2. Change the Background colour to '17·17·17' which is #222 in hex.
3. Change the Foreground colour to '128·128·128' which is #808080 in hex.
