### ISSUE TITLE
White screen flash despite using Dark Mode

### ISSUE THREAD

**Issue by bykidi** [notepad-plus-plus/notepad-plus-plus#11960]
Topic name. When you first open up the Notepad++, it flashes white before finally going black, as set up in the settings.
If there is something that could be done to this, this would be great

**Comment by ArkadiuszMichalski** [comment]
This should be fixed by https://github.com/notepad-plus-plus/notepad-plus-plus/pull/10639.

@bykidi Put your debug info.

**Comment by bykidi** [comment]
actually, i can no longer reproduce the issue... version is still the same.
i'll reopen if this happens again.
