### ISSUE TITLE
Delimiter selection crashes program

### ISSUE THREAD

**Issue by przemo20** [notepad-plus-plus/notepad-plus-plus#12384]
### Description of the Issue

Setting open and close characters to quotation mark ("), and then double clicking with the left mouse button while holding the Ctrl key on the last empty line in a file crashes the program.

### Steps to Reproduce the Issue

1. Go to: Settings → Preferences... → Delimiter → Switch open and close characters to quotation mark (") and close the Preferences window.
2. Create new document (Ctrl + N), type something and press Enter to create a new line
3. While holding the Left Control key, double click your left mouse button on the empty line
4. Program should now close itself

### Expected Behavior

Program should not select anything (as nothing matches) and not close itself.

### Actual Behavior

Program crashes.

### Debug Information

Notepad++ v8.4.6   (64-bit)
Build time : Sep 25 2022 - 19:51:39
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 22H2
OS Build : 19045.2130
Current ANSI codepage : 1252
Plugins : 
    ComparePlus (1)
    mimeTools (2.8)
    NppConverter (4.4)
    NppExport (0.4)

Video: https://www.youtube.com/watch?v=RSd6CAQn8gk

**Comment by Yaron10** [comment]
It seems that the crash occurs if Open and Close contain the same character. _Any character._

**Comment by xomx** [comment]
It crashes at this [line](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/cd6a6ac3bb4d46a9ddd53e3bde2002db00ac00f5/PowerEditor/src/NppNotification.cpp#L746):

`if (bufstring.at(i) == nppGUI._leftmostDelimiter)`

because of the `std::string bufstring` is an empty string ("") there, so calling the `bufstring.at(0)` is nonsense (there is no such `char` at that position to return from an empty string, so it throws an out of range ... "invalid string position" )

Maybe an additional check for empty `bufstring` there should do it (check also two other occurrences of the `bufstring.at(i)` further in the code).

If someone else could make a PR, I will be glad.

**Comment by prez2307** [comment]
Hi, I believe I've fixed this issue. I added a check at line 746 right before `if (bufstring.at(i) == nppGUI._leftmostDelimiter)` checking if bufstring was empty. This way, we don't get a bad access. In the other few occurrences of `if (bufstring.at(i) == nppGUI._leftmostDelimiter)` , the loops use `bufstring.length()` as a condition in the for loop, so when it is empty these loops don't run anyway, therefore we don't really need to check if `bufstring` is empty before that. 

Here is my very simple addition: 
<img width="269" alt="Screen Shot 2022-11-28 at 7 10 36 PM" src="https://user-images.githubusercontent.com/86853355/206279421-1f98e74d-3f2f-472a-b1a5-854cfd35de72.png">

**Comment by prez2307** [comment]
Hi, I believe I've fixed this issue. I added a check at line 746 right before `if (bufstring.at(i) == nppGUI._leftmostDelimiter)` checking if `bufstring` was empty. This way, we don't get a bad access. In the other few occurrences of `if (bufstring.at(i) == nppGUI._leftmostDelimiter)` , the loops use `bufstring.length()` as a condition in the for loop, so when it is empty these loops don't run anyway, therefore we don't really need to check if `bufstring` is empty before that.

Here is my very simple addition:
<img width="871" alt="Screen Shot 2022-12-07 at 2 41 15 PM" src="https://user-images.githubusercontent.com/86853355/206279695-2dbb1660-7830-41e6-af7c-fd24c72c285b.png">

**Comment by xomx** [comment]
@prez2307 
I was glad that someone else will handle that, but your solution proposed is still crashing at some circumstances. More in your PR.

**Comment by donho** [comment]
> I was glad that someone else will handle that, but your solution proposed is still crashing at some circumstances. More in your PR.

@xomx We call that "Shooting in the dark".
Not even the PR has not been tested, I wonder if the crash has been reproduced before making the PR in question.
For such reason all PR are selective - too many tourists/impostors here and I don't want the bad quality code into our repository, and I have no time for such people.
