### ISSUE TITLE
Two identical "Edit with Notepad++" appear in Total Commander

### ISSUE THREAD

**Issue by FanXiangTM** [notepad-plus-plus/notepad-plus-plus#13491]
Portable version of Notepad++: After executing the command "regsvr32.exe NppShell.dll", two identical "Edit with Notepad++" menus will appear in Total Commander.

This only happens on Windows 11 systems

**Comment by Districtor** [comment]
Directory Opus is affected as well:

[](https://resource.dopus.com/t/double-entry-of-edit-with-notepad-in-context-menu/44135)

**Comment by k-kolev1985** [comment]
Same goes for SpeedCommander - it also displays two "Edit with Notepad++" entries in the context menu.
Both SpeedCommander and Notepad++ are installed and are 64-bit versions on a 64-bit Windows 11.

**Comment by icegull** [comment]
Directory Opus can see two ""Edit with Notepad++" too with notepad++ 8.5.2

**Comment by donho** [comment]
@FanXiangTM @k-kolev1985 @icegull @Districtor 
Could you try 
http://download.notepad-plus-plus.org/repository/MISC/nppShell.TEST19/
?
This issue should be fixed by @GurliGebis and TEST19 contains the fix.

**Comment by Districtor** [comment]
Installed the test build without uninstalling Notepad++(8.5.2), both entries in the context menu still exist in Directory Opus, however one of the entries is now nonfunctional. Before, both entries would open the selected file in Notepad++.

**Comment by GurliGebis** [comment]
@Districtor can you try rebooting, and see if the issue persists?

**Comment by Districtor** [comment]
> @Districtor can you try rebooting, and see if the issue persists?

Rebooted, no change.

**Comment by GurliGebis** [comment]
@Districtor it loads the menu items in reverse order compared to the other programs I have tested, so that is the reason.
I don't think there is a good way to solve that, without ending up with people having no Edit with Notepad++ entry sometimes.

**Comment by GurliGebis** [comment]
This is due to them building their own right click menu, so they do it in the reverse order, so nothing we can do about it.

**Comment by Districtor** [comment]
> This is due to them building their own right click menu, so they do it in the reverse order, so nothing we can do about it.

Thank you for your efforts! Notepad++ is a great program.

**Comment by LeoDavidson** [comment]
Workaround for Directory Opus users:

Double-click **Preferences / Miscellaneous / Advanced [Troubleshooting]: ignore_context_menus** and add `NotepadPlusPlus_*` to it to remove the duplicate menu item.

We'll block the duplicate shell extension by default in the next Opus update.

**Comment by GurliGebis** [comment]
@LeoDavidson thanks, that would be great 🙂

For the interested people, here is the debug log of what is happening when you SHIFT+RIGHTCLICK on a file in Explorer in Windows 11:

```
ModernEditWithNppExplorerCommandHandler::ctor: Creating object
ClassicEditWithNppExplorerCommandHandler::ctor: Creating object
SharedState::SetState: Set shared state to: 1
ModernEditWithNppExplorerCommandHandler::State: Current state: 1
ClassicEditWithNppExplorerCommandHandler::ctor: Creating object
SharedState::SetState: Set shared state to: 0
ClassicEditWithNppExplorerCommandHandler::State: Current state: 1
ClassicEditWithNppExplorerCommandHandler::~tor: Destroying object
ModernEditWithNppExplorerCommandHandler::~tor: Destroying object
ClassicEditWithNppExplorerCommandHandler::~tor: Destroying object
```

And here is the debug log from when right clicking within opus:

```
ClassicEditWithNppExplorerCommandHandler::ctor: Creating object
SharedState::SetState: Set shared state to: 0
ClassicEditWithNppExplorerCommandHandler::State: Current state: 0
ModernEditWithNppExplorerCommandHandler::ctor: Creating object
SharedState::SetState: Set shared state to: 1
ModernEditWithNppExplorerCommandHandler::State: Current state: 1
ClassicEditWithNppExplorerCommandHandler::~tor: Destroying object
ModernEditWithNppExplorerCommandHandler::~tor: Destroying object
```

The order of the State function calls is swapped for some reason 🙂
If I switch the checks around, it won't show up in the modern right click menu, since it does this:

```
ClassicEditWithNppExplorerCommandHandler::ctor: Creating object
ClassicEditWithNppExplorerCommandHandler::ctor: Creating object
SharedState::SetState: Set shared state to: 0
ClassicEditWithNppExplorerCommandHandler::State: Current state: 0
ClassicEditWithNppExplorerCommandHandler::~tor: Destroying object
ModernEditWithNppExplorerCommandHandler::ctor: Creating object
SharedState::SetState: Set shared state to: 1
ModernEditWithNppExplorerCommandHandler::State: Current state: 1
ClassicEditWithNppExplorerCommandHandler::~tor: Destroying object
ModernEditWithNppExplorerCommandHandler::~tor: Destroying object
```

Unfortunately we have to have both the classic and modern installed on Windows 11, since some people are missing the modern entry in the classic menu (for some unexplained reason, that we cannot replicate)

**Comment by GurliGebis** [comment]
And since we have to work on downlevel Windows where only the classic menu exists, things get really complicated 😀

**Comment by xroberx** [comment]
I installed a fresh Windows 11 iso with the latest updates on VirtualBox and this issue is also present with Notepad 8.5.2
![Screenshot 2023-04-20 130003](https://user-images.githubusercontent.com/1663186/233348702-0c764b16-10dd-4a99-8653-f9e4e8d4df34.png)

**Comment by GurliGebis** [comment]
@xroberx can you try the installer in here: http://download.notepad-plus-plus.org/repository/MISC/nppShell.TEST20/ - does that work better?

**Comment by GurliGebis** [comment]
@xroberx is it when right clicking on the file in explorer? (normal or shift right click)

**Comment by xroberx** [comment]
> @xroberx is it when right clicking on the file in explorer? (normal or shift right click)

Just right click.

**Comment by GurliGebis** [comment]
@xroberx It sounds like the StartAllBack manipulates how things work somehow.
Can you try installing another VM, and then test in there without installing StartAllBack - to see if that is the cause of it?

**Comment by xroberx** [comment]
> @xroberx It sounds like the StartAllBack manipulates how things work somehow. Can you try installing another VM, and then test in there without installing StartAllBack - to see if that is the cause of it?

This is what I see without StartAllBack installed before right clicking on the sample text file:


![Screenshot 2023-04-21 113728](https://user-images.githubusercontent.com/1663186/233603810-841c9fde-1e33-4fd3-af32-a04662bab3f4.png)

As you can see, there are two entries, one at the top called Open and one at the bottom called Edit with Notepad++. Then, if I click on Show More Options at the bottom, I get the following:

![Screenshot 2023-04-21 113821](https://user-images.githubusercontent.com/1663186/233604326-6e71087b-dcbf-418c-9679-aa95af46fae0.png)

Again, two entries for Notepad++, one of them greyed out.

**Comment by GurliGebis** [comment]
Hmm, I wonder if it is related to txt files being associated with Notepad++.
Can you try without associating the .txt extension with Notepad++ ?

**Comment by xroberx** [comment]
> Hmm, I wonder if it is related to txt files being associated with Notepad++. Can you try without associating the .txt extension with Notepad++ ?

I removed the association from within Notepad++, associated .txt files with Windows Notepad and rebooted the system. Now I get the following when right clicking on a .txt file:

![Screenshot 2023-04-21 161053](https://user-images.githubusercontent.com/1663186/233659215-de1f21ad-8283-4980-a3c8-09e68bb2d2b7.png)

If I click on Show More Options, I still get two Notepad++ entries. This is really odd, because this only happens inside VirtualBox, but not on a regular Windows installation. And before you ask, yes, the Windows version is exactly the same.

**Comment by GurliGebis** [comment]
I'll take a look at it.

**Comment by xroberx** [comment]
> I'll take a look at it.

I did some more testing today... I installed Windows 11 **21H2** on both VirtualBox and VMWare, and I can confirm that the double entry issue is present even with the latest updates (version **21H2** compilation 22000.1817). 

Then I installed Windows **22H2** on VMWare and the double entry issue is not present with or without the latest updates. 

The thing is that there is no double entry when running Windows **21H2** with direct hardware access (no virtual machine involved). This baffles me.

**Comment by GurliGebis** [comment]
@xroberx can you try in VirtualBox without the drivers it provides?

**Comment by GurliGebis** [comment]
Hmm, my guess is that 21H2 does it differently than 22H2.
Unfortunately I don't see a way to solve this, since it will break other things if we change how it works.
The issue is that some people's system seems to be broken, so we have to install the context menu in two ways on Windows 11, to ensure it is there in both the new and classic right click menu, which is what is causing the double entries, if things are done in reverse (which seems to be the case for 21H2)
However, support for 21H2 is going away for Home and Pro in October, so by then most people would have been migrated.

**Comment by icegull** [comment]
> Workaround for Directory Opus users:
> 
> Double-click **Preferences / Miscellaneous / Advanced [Troubleshooting]: ignore_context_menus** and add `NotepadPlusPlus_*` to it to remove the duplicate menu item.
> 
> We'll block the duplicate shell extension by default in the next Opus update.

Good point.

**Comment by NicklasP-Derivco** [comment]
Having this exact issue on 8.5.3 (64 bit x64)

Windows 11 - Build 22000

**Comment by GurliGebis** [comment]
@donho can we combine this issue with #13296 - they are relating to the same thing? (Just so we don't have too many issues about it to keep track of)

**Comment by pryrt** [comment]
another instance [in the wild](https://community.notepad-plus-plus.org/topic/24740/edit-with-notepad).

**Comment by p1r473** [comment]
Im still having this issue with WIndows Explorer on Windows. Reinstall did not fix.

**Comment by coreanho** [comment]
Hello,

I resolved this issue by unregistering the NppShell_06.dll file. Here are the steps I followed:

1. First, ensure that you have the NppShell_06.dll file:

- Install Notepad++ version 8.4.9 (or another older version).

2. Install the latest Notepad++ version (e.g., 8.5.7) alongside the older version.

Now, you will have two files:

- "[Notepad++ Install Path]/NppShell_06.dll"
- "[Notepad++ Install Path]/contextMenu/NppShell.dll"

3. Unregister the "NppShell_06.dll" file using this command:

`regsvr32 /u [Notepad++ Install Path]/NppShell_06.dll`
(You will need Administrator privileges for this step.)

After completing these steps, the grayed-out "Edit with Notepad++" context menu should no longer be visible.

I hope this explanation is helpful to all experiencing this issue.

**Comment by jmada** [comment]
> Hello,
> 
> I resolved this issue temporary by unregistering the NppShell_06.dll file. Here are the steps I followed:
> 
>     1. First, ensure that you have the NppShell_06.dll file:
> 
> 
>     * Install Notepad++ version 8.4.9 (or another older version).
> 
> 
>     2. Install the latest Notepad++ version (e.g., 8.5.7) alongside the older version.
> 
> 
> Now, you will have two files:
> 
>     * "[Notepad++ Install Path]/NppShell_06.dll"
> 
>     * "[Notepad++ Install Path]/contextMenu/NppShell.dll"
> 
> 
>     3. Unregister the "NppShell_06.dll" file using this command:
> 
> 
> `regsvr32 /u [Notepad++ Install Path]/NppShell_06.dll` (You will need Administrator privileges for this step.)
> 
> After completing these steps, the grayed-out "Edit with Notepad++" context menu should no longer be visible.
> 
> I hope this explanation is helpful to all experiencing this issue.

Thank you so much, this worked for me. I ran the following command in my CMD terminal with administrator privileges: `regsvr32 /u "C:\Program Files\Notepad++\NppShell_06.dll"`. It fixed the issue in both Total Commander and Windows Explorer.
