### ISSUE TITLE
Context menu entry greyed out on Win10

### ISSUE THREAD

**Issue by w3lld0ne** [notepad-plus-plus/notepad-plus-plus#13568]
### Description of the Issue

Context menu entry in Explorer's menu is greyed out & unclickable.
![image](https://user-images.githubusercontent.com/14851973/233787957-bd0617c0-3919-4796-ad2b-122e69967085.png)

I'm using Directory Opus almost all the time so I can't tell when it started to be like that. In DOpus' context menu it's perfectly fine.

Also, I've found there is a [similar problem with Win11's context menu issue](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/13491#issuecomment-1517567293), but I'm on Win10 22H2 and I have only one context menu entry.

**Comment by GurliGebis** [comment]
I'll take a look at it.

**Comment by GurliGebis** [comment]
@w3lld0ne Can you try with the TEST20 version link in the issue you link to, just to see if it is already fixed?

**Comment by w3lld0ne** [comment]
> @w3lld0ne Can you try with the TEST20 version link in the issue you link to, just to see if it is already fixed?

I'm still on the stable version today, but context menu entry works fine now. I'm not sure what could have fixed it or what could have broke it before.

If I'd receive this behaviour again, I will try TEST20 branch.

**Comment by GurliGebis** [comment]
Okay, if not, I don't think there is a way to debug the issue.

**Comment by BenSokolGarmin** [comment]
I'm seeing this as well on Windows 10 22H2.
Notepad++ 8.5.2 (64-bit)

**Comment by w3lld0ne** [comment]
@BenSokolGarmin can you try the version from here: http://download.notepad-plus-plus.org/repository/MISC/nppShell.TEST20/ ?

**Comment by tarekahf** [comment]
I am using NP++ 32 bit. I  [installed this one](http://download.notepad-plus-plus.org/repository/MISC/nppShell.TEST20/npp.8.5.2.Installer.exe) and the problem was not resolved.

**Comment by Wacky-Mole** [comment]
Yes, it is still an issue with 8.5.3

**Comment by NicklasP-Derivco** [comment]
Having this issue on 8.5.3 (64 bit x64)

**Comment by GurliGebis** [comment]
Can you please try and attach a screenshot of what you are seeing?
I cannot reproduce the issue on my test machine ☹️

**Comment by NicklasP-Derivco** [comment]
@GurliGebis - apologies - I did try initially as well, however my organization blocks uploads.

After some searching I realized this is my exact* issue:
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/13491#issuecomment-1517567293

Double entry, 1 greyed out, 1 does nothing.

I´ll just have to stick it out until an update is pushed to resolve.
Not critical in my case.

**Comment by billyhtchcoc** [comment]
I'm having the same issue myself.  It npp isn't greyed out when I'm trying to edit standard .txt files with the program, but when I go to edit a .ini file using the context menu it's greyed out.

Possibly that will help track down the issue?

**Comment by SMSourov** [comment]
@GurliGebis I had the same issue and I somehow solved it.
I had v 8.5.2 installed. Here is what I did before the appearance of the problem: 
1. Opened Windows Security.
2. Went to Device Security.
3. Went to Core isolation details.
4. Turned on Memory integrity.
5. Restarted my PC.

I just wanted to enforce extra security in my PC. I was unaware about this problem.

Here is what I did to resolve the problem.
1. Uninstalled Notepad++ v8.5.2 using Bulk Crap Uninstaller.
2. Installed Notepad++ v8.5.4.
3. Check the context menu. I saw that the problem is present.
4. Turned off Memory integrity from the Device Security in Windows Security.
5. Restarted my PC.
6. Check the context menu. I saw that the problem was solved.

You can try to reproduce and solve the problem in this way.

**Comment by tstauffer** [comment]
i am having the same issue on 8.5.4.  I just noticed this today

**Comment by tarekahf** [comment]
> @GurliGebis I had the same issue and I somehow solved it. I had v 8.5.2 installed. Here is what I did before the appearance of the problem:
> 
> 1. Opened Windows Security.
> 2. Went to Device Security.
> 3. Went to Core isolation details.
> 4. Turned on Memory integrity.
> 5. Restarted my PC.
> 
> I just wanted to enforce extra security in my PC. I was unaware about this problem.
> 
> Here is what I did to resolve the problem.
> 
> 1. Uninstalled Notepad++ v8.5.2 using Bulk Crap Uninstaller.
> 2. Installed Notepad++ v8.5.4.
> 3. Check the context menu. I saw that the problem is present.
> 4. Turned off Memory integrity from the Device Security in Windows Security.
> 5. Restarted my PC.
> 6. Check the context menu. I saw that the problem was solved.
> 
> You can try to reproduce and solve the problem in this way.

Thank you but I'd rather live with the problem over implementing the steps... 😂

**Comment by chladnefazole** [comment]
> @GurliGebis I had the same issue and I somehow solved it. I had v 8.5.2 installed. Here is what I did before the appearance of the problem:
> 
> 1. Opened Windows Security.
> 2. Went to Device Security.
> 3. Went to Core isolation details.
> 4. Turned on Memory integrity.
> 5. Restarted my PC.
> 
> I just wanted to enforce extra security in my PC. I was unaware about this problem.
> 
> Here is what I did to resolve the problem.
> 
> 1. Uninstalled Notepad++ v8.5.2 using Bulk Crap Uninstaller.
> 2. Installed Notepad++ v8.5.4.
> 3. Check the context menu. I saw that the problem is present.
> 4. Turned off Memory integrity from the Device Security in Windows Security.
> 5. Restarted my PC.
> 6. Check the context menu. I saw that the problem was solved.
> 
> You can try to reproduce and solve the problem in this way.

I already have Notepad++ v8.5.4, and memory integrity is already turned off, and I have the greyed-out menu problem.

**Comment by GurliGebis** [comment]
Lets wait for the next release, where I have implemented logging for the context menu DLL, so we hopefully can see what is happening.

**Comment by John-Riley-TSI** [comment]
In my case, I noticed that out of 6 open Explorer windows, two had NppShell.dll open and the rest didn't. One of those was a windows into Administrative Tools. The one in Admin Tools had a visible context menu entry, the other one did not. I Opened a second Admin Tools window and it's entry was greyed out.

I ran explorer from a DOS window run as Administrator. After navigating to the original directory with the greyed-out entry, it was now usable.

Have no idea what this means, but FYI...

**Comment by dehlirious** [comment]
Same issue just happened to me. Was working just fine now it's greyed out. 

After restarting Explorer, as admin, fixed the issue. Not sure if it's specific to admin, or if explorer just bugged out and needed restarting, but No other items were greyed out, Only Edit with Notepad++

**Comment by tarekahf** [comment]
I installed latest version  np++ 23 bit. The problem keeps on happening randomly. It is fine time then all of a sudden, it's greyed out, then after sometime, it's back. I can't find a pattern.

**Comment by GurliGebis** [comment]
@dehlirious and @tarekahf, we have an installer with some debugging enabled.
Will you try and install it and send me the logfile?

The installer is here: http://download.notepad-plus-plus.org/repository/MISC/nppShell_more_log/
Here is how to enable logging and finding the logfile:

First, you create an new environment variable called NPPSHELL_LOGGING_ENABLED and set it to true
Then you kill explorer.exe using task manager, so it restarts (or restart the computer)
After that, you reproduce the issue.
Finally, inside your Roaming AppData folder, you should find a NppShell folder, with the logfile

**Comment by tarekahf** [comment]
Sure, will try to do that on Monday.

**Comment by junk430** [comment]
I have several Citrix users who are just now reporting this being an issue for them. I'll see if I can get this client pushed to the Citrix boxes and set the variable for the user.
Server 2022
Citrix VDA 2203

**Comment by GurliGebis** [comment]
@junk430 it doesn't matter, system is available for all users on the system, while user is only the specific user

**Comment by junk430** [comment]
Thanks @GurliGebis. It seems my AWX job didn't install the special build even though it said it did. I'll have to get that installed.

**Comment by tarekahf** [comment]
I managed to install the latest version with debug features, now waiting to reproduce the problem...

**Comment by GurliGebis** [comment]
@tarekahf great, thanks :)

**Comment by tarekahf** [comment]
Note that in one ocasion, I saw the option switching over from normal to gray in a couple of seconds (right-click/edit in NP++). There is a possibility that there is something disabling this option on the fly like company policy. I never had this problem in the past, only when I installed a new version. Note that this latest version is not listed on the approved apps by the in-house official portal.

**Comment by John-Riley-TSI** [comment]
Whenever I've seen it, I can always work around it by starting an elevated DOS shell, cd'ing to the desired directory and typing "explorer ." It also appears that, while it is quite random in it's occurrence, once it starts doing that new unelevated Windows Explorer windows continue to come up with the context menu item greyed out.

**Comment by tarekahf** [comment]
Ops, I forgot to set the env var:

![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/20842027/7fac0111-2599-4dd1-a722-dcb0f9b0180c)

Is that above the correct way?

**Comment by tarekahf** [comment]
> The installer is here: http://download.notepad-plus-plus.org/repository/MISC/nppShell_more_log/ Here is how to enable logging and finding the logfile:
> 
> First, you create an new environment variable called NPPSHELL_LOGGING_ENABLED and set it to true Then you kill explorer.exe using task manager, so it restarts (or restart the computer) After that, you reproduce the issue. Finally, inside your Roaming AppData folder, you should find a NppShell folder, with the logfile

@GurliGebis
I am not finding the NppShell folder. Please provide the exact path.

**Comment by tarekahf** [comment]
@GurliGebis 

I found the log file, and attached here. See below. Also, I included two snapshots, one when it is dimmed, and another when I opened explorer using admin and it is not dimmed.

![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/20842027/139bfef1-9a58-489a-88d7-e415cf6f66f0)

![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/20842027/3613b643-f8f0-40b6-9a40-d96c39440b35)

[NppShell.log.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/13242872/NppShell.log.txt)

**Comment by dehlirious** [comment]
> Will you try and install it and send me the logfile?
> 
> The installer is here: http://download.notepad-plus-plus.org/repository/MISC/nppShell_more_log/
> Here is how to enable logging and finding the logfile:
> 
> First, you create an new environment variable called NPPSHELL_LOGGING_ENABLED and set it to true
> Then you kill explorer.exe using task manager, so it restarts (or restart the computer)
> After that, you reproduce the issue.
> Finally, inside your Roaming AppData folder, you should find a NppShell folder, with the logfile

I failed to do this, my bad, but I did notice something 

It seems to be an explorer bug that happens to affect notepad for some reason.

When this happened the second time to me, explorer could not accurately list how many files were in the folder. Regardless of what folder I went to, it said "61" files and notepad++ was greyed out.

**Comment by GurliGebis** [comment]
@dehlirious okay, so it seems to be an explorer bug.
That's annoying, since that isn't something I really can do much about 😟

**Comment by dehlirious** [comment]
> @dehlirious okay, so it seems to be an explorer bug.
> That's annoying, since that isn't something I really can do much about 😟

But why, why, does it only do it to notepad++ is my question? What's unique about the implications? It won't remove my take ownership reg mod, or doesn't affect 7zip, doesn't remove the default notepad edit button, only notepad++.  
It's so odd

**Comment by GurliGebis** [comment]
That is also what I'm wondering about.
The implementation is pretty much identical to Microsofts example, so it should be working.
Most likely it is something else that is causing it to fail, for some reason (I have tested it in a clean Win10 VM, and it seems to be working fine).

Can you try using the Windows Sandbox on your machine, and install Notepad++ in there, and see if the problem is there? (The sandbox is a clean VM that is cleaned every time it is closed).

**Comment by Girofox** [comment]
How do you even open explorer as admin? On Windows 11 this seems impossible, even when you end explorer.exe in task manager and start new task as admin.

**Comment by dehlirious** [comment]
> How do you even open explorer as admin? On Windows 11 this seems impossible, even when you end explorer.exe in task manager and start new task as admin.

Don't use taskmgr, that simple.  Lookup "process explorer" , will be a Microsoft website.  Click the menu, restart process explorer as admin, via the top left menu drop down, then restart the explorer.exe task and it'll be ran as admin.  Task manager is garbage unfortunately, it's a shame they moved the startup menu to taskmgr instead of where it was located in "msconfig" next to the startup services.  Now you have a false pretense that you disabled all startup tasks when in reality there's extra services being ran ++ you still have to go to Task Scheduler to disable further bloat ware (like if you install chrome, disable the chrome update task entirely and whatnot, it's senseless to have these programs running in the background without your knowledge or inherent consent)

**Comment by tarekahf** [comment]
I want to mention that I feel that OneDrive sync or indexing process might be interfering and causing this issue. In many instances I saw the greyed out NPP option getting enabled on the spot while the explorer refresh is completed. It seems the refresh takes several minutes probably due to network delays, indexing process, or OneDrive sync status update. Sometimes I leave the explorer window open for say 1 hour, I come back to the same window and the problem is resolved.

**Comment by Girofox** [comment]
In my case the greyed out option randomly turns normal after some time too but i don't have OneDrive running. But OneDrive Sync is an extra Windows App and is heavily integrated into Explorer though.

**Comment by tarekahf** [comment]
> In my case the greyed out option randomly turns normal after some time too but i don't have OneDrive running. But OneDrive Sync is an extra Windows App and is heavily integrated into Explorer though.

I think the logic used to implement the enable/disable of this NPP option is waiting for some information about the file selected during right-click and the needed info takes a long time to be fetched.

**Comment by GurliGebis** [comment]
@tarekahf It isn't looking at anything about the file when you right click it, so I don't think that is the case.

**Comment by tarekahf** [comment]
> @tarekahf It isn't looking at anything about the file when you right click it, so I don't think that is the case.

@GurliGebis I'm seeing possible correlation between windows explorer refresh progress bar and this issue so I'm just guessing. The explorer take forever to complete the refresh progress bar and I'm thinking this affects the right-click logic.

**Comment by tarekahf** [comment]
@GurliGebis I am now nearly confident that there is some process taking place when you open Windows Explorer. If this happens, you will notice that the ribbon view/layout section is inactive or partly active. At this time, the right-click NPP issue will be triggered. As soon as the view/layout section is fully active, the NPP right-click issue is resolved (will be active). I believe this is similar or related to what you have observed that the file count is not correct.

Test: wait until the issue is triggered. Check the view/layout ribbon section in File Explorer and you will notice t's not active. Click around in this ribbon section to stimulate the process, and refresh, wait, and try again. You will see that the issue will be resolved in a few moments. I was able to reproduce this behavior several times. I am guessing it's either Indexing Service or something else running in the background like activity monitor or similar which is interfering with this issue.

**Comment by GurliGebis** [comment]
In that case, I don't see what we can do about it - do you happen to have any ideas?

**Comment by tarekahf** [comment]
> In that case, I don't see what we can do about it - do you happen to have any ideas?

Yes that's true, but why the right-click "open with" option always works even with NPP and the issue never causes this option to be greyed out?

And, I'm happy with what I have and thank you for your reply.

**Comment by GurliGebis** [comment]
That is what I'm wondering as well.

You're welcome :)

**Comment by taserian** [comment]
Adding what solved it in my case:

Check to see if you have [Nilesoft Shell installed.](https://github.com/moudey/Shell)
If you do, see this issue here: https://github.com/moudey/Shell/issues/347

**Comment by GurliGebis** [comment]
I think we should default to asking people, if they have anything weird installed, and if so, to uninstall and test again 🙂

**Comment by dehlirious** [comment]
> I think we should default to asking people, if they have anything weird installed, and if so, to uninstall and test again 🙂

The issue for me was explorer.exe, that's what caused the issue. Explorer would get laggy or perform weirdly. Restarting it helped. Doesn't seem like anything notepad++ can control. Nothing weird installed.  Haven't had this issue in a while now.  I don't know exactly what caused explorer to behave weirdly.

**Comment by John-Riley-TSI** [comment]
For what it's worth, I believe that Windows Explorer is the culprit. It does get hung up grinding on something and at that point the only thing I can do is start a new Windows Explorer running as Administrator or reboot. While this is happening, I can search for a file using FileLocator Pro (Agent Ransack). When I right click on the file the "Edit with Notepad++" works out of the context menu.

Unless there is some other way to use the API which presents the context menu from Notepad++, I can't see what you could possibly do about it. 

That being said, I have other applications (e.g., WinMerge), which don't exhibit the context menu problem, perhaps they are taking a different route to implement?

**Comment by nohart** [comment]
> Adding what solved it in my case:
> 
> Check to see if you have [Nilesoft Shell installed.](https://github.com/moudey/Shell) If you do, see this issue here: [moudey/Shell#347](https://github.com/moudey/Shell/issues/347)

What file did you put the code in?

**Comment by armandxg** [comment]
I did the following solution:  I lopesoft's filemenutools installed because the extra functions are nice. So I added a menu choice edit with notepad++   Works just as well as the nppshell option. Another option is easy context menu;
Lopesoft filemenutools: [https://www.sordum.org/7615/easy-context-menu-v1-6/https://www.sordum.org/7615/easy-context-menu-v1-6/](url)
Sordun Easy Context menu[https://www.lopesoft.com/index.php/en/filemenutools/fmtools-download](url)

I do use the NileSoft Shell I just wanted to provide choices.

**Comment by av930** [comment]
This problem is still occurred before 1 weeks. I don't know why..
I reinstalled newest version and others, Nothing is changed.

**Comment by John-Riley-TSI** [comment]
At some point a while ago, the problem went away "by itself" Not sure why, but I did see a correlation to a different symptom at the same time, It used to be, when I clicked on "Desktop" it used to take forever for Explorer to load everything (progress bar, etc.). One day it stopped doing that, no doubt something that IT did, but I don't know what and after that I've never seen it again.

**Comment by wtfiwinomgs** [comment]
issue is to do with explorer.exe, restart it and it is solved, not sure why though

**Comment by VL4DST3R** [comment]
Still an issue to this day, restarting the explorer does indeed fix it, but seems to happen when you get those mysterious "infinitely loading" green progress bars on the address bar.
