### ISSUE TITLE
find and replace spaces not removing them despite saying x amount replaced

### ISSUE THREAD

**Issue by perlsol** [notepad-plus-plus/notepad-plus-plus#14419]
### Description of the Issue
find and replace spaces in large files, it will find them and say x amount replaced however it does not replace them

### Steps to Reproduce the Issue
open large file, search for 1 space, replace all

### Expected Behavior
all spaces should be replaced

### Actual Behavior
the spaces remain

### debug info
Notepad++ v8.5.8   (64-bit)
Build time : Oct 15 2023 - 21:43:56
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : "C:\ipfreely\iplister2.txt"
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit)
OS Version : 22H2
OS Build : 19045.3693
Current ANSI codepage : 1252
Plugins : 
    DSpellCheck (1.4.24)
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)

### more info
I have this installed on a few machines I use and it only does this on the latest few versions,
I noticed this on the previous version so updated to the latest to find it still a problem

It does not do this on v8.4.5 and works as expected.

this bug applies to all search modes

**Comment by perlsol** [comment]
It does not have to be a large file, I also tried to replace the spaces from a small list of ip address I copied,
this has a space before the first IP, after each IP, but not the last IP.

attached example...
[spaces.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/13487738/spaces.txt)

**Comment by perlsol** [comment]
I should also add that I am attempting to replace them with nothing, to simply remove all spaces

**Comment by alankilborn** [comment]
It works fine for me to remove all spaces.

You probably have _Match whole word only_ checkmarked.  If so, uncheckmark it.
If that's not the case, probably show a screenshot of your _Replace_ window, right before you press _Replace All_.
Maybe also an "after" screenshot, if you see some nonzero number of replacements made in the _Replace_ window status bar.

**Comment by perlsol** [comment]
I appreciate your help and testing, as I have to copy this to another machine to replace the spaces then copy it back, both machines have the same search settings.

in grab, I have highlighted the space in the search find field to indicate it is indeed just a space.
in grab1, I highlighted some to show the trailing spaces still remain despite it sayin 59 occurrences were replaced

grab is before, grab1 is after

![grab](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/6700023/9606c0d9-2599-4b6b-88b6-1edb318a0f99)
![grab1](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/6700023/ea06a9a1-60b9-4e39-8f84-714425e12644)

**Comment by alankilborn** [comment]
Cannot replicate in 8.5.8.

Here's what it looks like for me _before_:

![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/77065706/30729f92-123d-4f72-9462-1bb0c42755bd)

and _after_:

![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/77065706/e1f24b26-fb11-4c04-b2bd-4e083c0e7be0)

Strangely, my selected _Find what_ text looks slightly wider than yours (but maybe it is an optical illusion).  Are you sure that what you have there is a single normal space character?  Maybe try getting input focus in that box, pressing Ctrl+a, and then do a single press of the spacebar?

**Comment by perlsol** [comment]
I tried "pressing Ctrl+a, and then do a single press of the spacebar", still says 59 replaced when it does not replace them.

I even tried searching by regex for "\s\n" and replace with "\n", again it says 59 replaced and it did not actually replace them, I have tried everything I can think of way before the idea of submitting this as an issue

**Comment by perlsol** [comment]
the only thing i notice that is different on each of my machine's, I only have the pluggin DSpellCheck (1.4.24) on this effected installation, it is not installed on all other machine's... wondering if this is causing it?

**Comment by perlsol** [comment]
Seems I was right, I just checked the pluggins and there was an update to v1.5, I updated and it restarted... now the spaces are actually being replaced :)

Thank you for all your efforts and time helping me to get to the bottom of this, hope you have a good day.

**Comment by alankilborn** [comment]
Hmm, had no idea that a spell-check plugin could affect replacement in such a way...wow.
Glad it is solved!

**Comment by perlsol** [comment]
merry Christmas... this problem is back, this time there are no updates

**Comment by alankilborn** [comment]
Remove DSpellCheck, attempt to reproduce, report results here.

**Comment by perlsol** [comment]
yep, removed said plugin and problem has gone, very strange that it just started doing this as I have been using it all day
