### ISSUE TITLE
Message "Secure Connection Failed" On Firefox 125 when accessing the site "https://notepad-plus-plus.org/"

### ISSUE THREAD

**Issue by BlackEagles2022** [notepad-plus-plus/notepad-plus-plus#14890]
### Description of the Issue

Secure Connection Failed

An error occurred during a connection to notepad-plus-plus.org. The OCSP response does not include a status for the certificate being verified.

Error code: MOZILLA_PKIX_ERROR_OCSP_RESPONSE_FOR_CERT_MISSING

    The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
    Please contact the website owners to inform them of this problem.

### Steps to Reproduce the Issue

1. open site "https://notepad-plus-plus.org/"

**Comment by xomx** [comment]
As the SSL certificate seems to be ok (one can open that page from the other browsers), it looks to me as the [OCSP Stapling](https://en.wikipedia.org/wiki/OCSP_stapling) response issue at the Notepad++ Certificate Authority side. It could be a temporary problem only, just try to wait some time. If the problem persists, the OCSP Stapling can by disabled via the Firefox "about:config" page (search there for the `enable_oscp` and set both items to `false`).

**Comment by AndiKiissel** [comment]
This is not Firefox problem, ESET Endpoint Security blocks in all browsers:

![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/107611105/f96bd4db-ca3a-4558-a9dd-6227be5595e2)

**Comment by xomx** [comment]
@AndiKiissel 
> This is not Firefox problem

Yes, it is not, I did not said it is. I only showed a way how to circumvent this temporarily in the Firefox browser.

What I tried to say is that the N++ certificate issuer CA has a OCSP network response problem. Anyway it seems to work now.

**Comment by donho** [comment]
It seems the the hosting provider has just renewed the SSL certificate for notepad-plus-plus.org.
The problem should be solved now. Please let me if the problem resists to you.

**Comment by AndiKiissel** [comment]
I'm not sure does ESET care about browser settings...
And the problem still not solved yet (16:15 GMT).

**Comment by kmpm** [comment]
Duplicate of #14623, and still not working
