### ISSUE TITLE
[BUG] Floating panels (E.g. Search results) position and size was changed after Notepad++ restart on multiple monitors environment.

### ISSUE THREAD

**Issue by DarkNami** [notepad-plus-plus/notepad-plus-plus#15498]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

I have 3 monitors.
Since version v8.6.9, If I moved "Search results window" to other screen (not same screen with Notepad++ window),
when I restart Notepad++, the "Search results window" will be moved to Notepad++ screen, position and size was changed.

![Schematic](https://github.com/user-attachments/assets/f1e80de8-6334-40d4-bec6-210623ce5fec)

### Steps To Reproduce

1. MENU > Search > Find
2. Click "Find All in Current Document".
3. If the "Search Results" is docking on Notepad++, undock it.
4. Move "Search Results" float window to other screen.
5. Exit Notepad++
6. Launch Notepad++
7. MENU > Search > Find
8. Click "Find All in Current Document".
9. The "Search Results" float window is displayed on the same screen as the Notepad++ window, position and size was changed.

### Current Behavior

The "Search Results" float window is displayed on the same screen as the Notepad++ window, position and size was changed.

### Expected Behavior

Don't change float window position and size if that is visibly on any screen.

### Debug Information

```shell
Notepad++ v8.6.9   (64-bit)
Build time : Jul 12 2024 - 05:09:25
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line :
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
Periodic Backup : ON
OS Name : Windows 10 Pro (64-bit)
OS Version : 22H2
OS Build : 19045.4651
Current ANSI codepage : 950
Plugins : 
    Explorer (1.9.5)
    LocationNavigate (0.4.8.1)
    mimeTools (3.1)
    NppConverter (4.6)
    NppExport (0.4)
```

### Anything else?

Reference:
#15357 
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/8beda66cb8c77361216a43075e9be44ca32edbec

I'm not familiar with C++, so I can't create a PR.
My personal opinion is that we need to consider the condition of multiple screens in [PowerEditor/src/Parameters.cpp](https://github.com/notepad-plus-plus/notepad-plus-plus/commit/8beda66cb8c77361216a43075e9be44ca32edbec#diff-3908832391e0c264ec9734b9594d266bef64fb355e92b96662c4ad655a366931) Line 6837 ~ 6870.

**Comment by brm121966** [comment]
I sometimes add to config.xml after restarting npp
            <FloatingWindow cont="6" x="2669" y="198" width="4974" height="1362" />
             <ActiveTabs cont="6" activeTab="0" />
                        
Notepad++ v8.6.9   (64-bit)
Build time : Jul 12 2024 - 05:09:25
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
Periodic Backup : ON
OS Name : Windows 10 Pro (64-bit)
OS Version : 22H2
OS Build : 19045.4894
Current ANSI codepage : 1251
Plugins : 
    HelloWorld (1)
    HTMLTag (1.3.5)
    LocationNavigate (0.4.8.1)
    mimeTools (3.1)
    NavigateTo (1.12.7)
    NppConverter (4.6)
    NppExport (0.4)
    NPPJSONViewer (1.40)
    NppMultiReplace (1)

**Comment by xomx** [comment]
@donho 
Please assign this to me.
It is a regression due to my patch for the lost panels problem #13084 .
I have already tested this problem in a multi-monitor env and I have a sln (just no time).

**Comment by Galenmacil** [comment]
I can confirm this is an annoyance on multi monitor setup. I reverted back to an older version just because of this issue... Hopefully, this will get fixed soon.

**Comment by xomx** [comment]
@DarkNami @brm121966 @Galenmacil 

Could you please test the fix binary?

Direct link to the GitHub Actions x64 Release `Notepad++.exe` binary for replacement of your `C:\Program Files\Notepad++\notepad++.exe`:
https://github.com/notepad-plus-plus/notepad-plus-plus/actions/runs/12821164085/artifacts/2444563967

**Comment by DarkNami** [comment]
```text
Notepad++ v8.7.5   (64-bit)
Build time : Jan 17 2025 - 01:59:06
Path : C:\Program Files\Notepad++\Notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
Periodic Backup : ON
Placeholders : OFF
DirectWrite : OFF
Multi-instance Mode : monoInst
File Status Auto-Detection : cdEnabledNew (for current file/tab only)
Dark Mode : OFF
OS Name : Windows 10 Pro (64-bit)
OS Version : 22H2
OS Build : 19045.5371
Current ANSI codepage : 950
Plugins : 
    Explorer (1.9.5)
    LocationNavigate (0.4.8.1)
    mimeTools (3.1)
    NppConverter (4.6)
    NppExport (0.4)
```
I tested.
I confirm this issue has been fixed, thanks.

**Comment by courtens** [comment]
The positioning retaining of the position has been fixed, but not the window dragging issues I have when moving the window to a different location. During the "hold" and "drag" state the window appears to the left of where I am holding it.

**Comment by xomx** [comment]
@courtens 
> The positioning retaining of the position has been fixed,

Good.

> but not the window dragging issues I have when moving the window to a different location. During the "hold" and "drag" state the window appears to the left of where I am holding it.

I see what you are talking about, but please continue with it in your original issue 16077, as this other issue of yours has nothing to do with the one here.

**Comment by Galenmacil** [comment]
I tested the beta EXE Notepad++.exe (version 8.7.5.0 dated 2025-01-17 02:01) and the problem is still present for me. I am not sure if this is relevant or useful but my monitors are in an asymmetrical configuration:

![Image](https://github.com/user-attachments/assets/7f346480-79f2-4659-a096-83d751708546)

The top left corner of the Monitor 2 viewport is at absolute coordinate (-1080, -975)
The top left corner of the Monitor 1 viewport is at absolute coordinate (0, 0)

**Comment by xomx** [comment]
@Galenmacil 

> I tested the beta EXE Notepad++.exe (version 8.7.5.0 dated 2025-01-17 02:01) and the problem is still present for me.

That's odd, could you please repeat your test with the standard v8.7.6 (where my fix was already incorporated)?
https://notepad-plus-plus.org/downloads/v8.7.6/

> I am not sure if this is relevant or useful but my monitors are in an asymmetrical configuration:

IDK, I'll try to reproduce it somehow if you confirm that the problem is still there in v8.7.6.

**Comment by courtens** [comment]
v8.7.6 retains the search window position, but it did not fix the windows "dragging" problem illustrated in the monitor layout image in post https://github.com/notepad-plus-plus/notepad-plus-plus/issues/16077#issuecomment-2599866202

**Comment by Galenmacil** [comment]
I can confirm that the problem I described here is fixed in version 8.7.6. Thank you!

**Comment by xomx** [comment]
@courtens 
> but it did not fix the windows "dragging" problem illustrated in the monitor layout image in post [#16077 (comment)](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/16077#issuecomment-2599866202)
> 
> **It looks to me that the floating window position is off to the left by the width of the left monitor.**

As I told you in https://github.com/notepad-plus-plus/notepad-plus-plus/issues/16077#issuecomment-2600807189 , until the N++ panels code is not modified to be hidpi compatible (& thus permonitor aware), there is nothing we can do with it.
