### ISSUE TITLE
Left/Right arrow key problem in RTL direction

### ISSUE THREAD

**Issue by mahpooya** [notepad-plus-plus/notepad-plus-plus#1556]
In Text Direction RTL mode the left and right arrow key are act conversely (opposite)
If i press Left arrow key the text cursor move Right
And if i press Right arrow key the text cursor move Left

**Comment by justanotheranonymoususer** [comment]
+1
I have encountered this issue too.
Should be fairly simple to fix.

**Comment by Nucs** [comment]
+1

**Comment by MedNait** [comment]
I encountered this problem too. Apparently it has to do with how scintilla handles RTL text.

According to this source:
https://sourceforge.net/p/scintilla/bugs/1590/
this bug was fixed. 

Is it possible to get a Scintilla update for notepad++ to solve this problem? Thanks

**Comment by EricBright** [comment]
Any update on this issue? I am curious what stage the progress is at. Any hope we might have it in the next release?

**Comment by MedNait** [comment]
No idea! The bug still exists though. Hope it will be fixed soon.

**Comment by daniel-shimon** [comment]
Hi, this issue has already been fixed in Scintilla by version 4.0.3 - released over one year ago..

@donho Is it possible to get such an update?
Many thanks 🙌

**Comment by MetaChuh** [comment]
partial rtl issues and cursor "mirrored mirroring" fixes would require an upgrade to a newer version of the scintilla project component.

currently we can not implement e.g. scintilla version 4.1.5 without a major workload, as it would break some notepad++ specific customisations, which have been done to 3.5.6 over the past years, to fulfil vanilla scintilla overriding feature requests.

thank you for your understanding and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Comment by justanotheranonymoususer** [comment]
> Hi, this issue has already been fixed in Scintilla by version 4.0.3 - released over one year ago..

Notepad++ 7.7: Scintilla, the main component of Notepad++ is upgraded from v3.56 to v4.14 in this version.

But it's still an issue.

**Comment by mahpooya** [comment]
I think RTL languages are ignored by npp developers.
And this is bad! :(
