### ISSUE TITLE
[BUG] File Explorer Unclickable Navigation Pane

### ISSUE THREAD

**Issue by Sammmy1036** [notepad-plus-plus/notepad-plus-plus#16977]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Description of the Issue

Can't click on anything in file explorer yet file explorer is not listed as "Not Responding" and you can still click in toolbar. 

Reddit users stated that uninstalling Notepad ++ fixes it. I just tried it and no longer having any issues. 

I'm experiencing this issue on 4 different computers all with Notepad ++. One of the PCs is brand new and started having the issue after installing Notepad ++. 

Didn't see this reported, so putting it up. 

https://www.reddit.com/r/WindowsHelp/comments/1m46cmp/cant_click_on_anything_in_file_explorer/

### Steps To Reproduce

1. Clicking on file explorer folder occasionally navigation tabs and folder selection window just stop allowing selection / navigation. 
2.  Window does not go "Not Responding" but you have to close out the window and open a new one to fix it. 

### Current Behavior

File explorer clicking navigation pane and folders in window sometimes are unclickable and makes it to where you need to open a new file explorer window entirely. 

### Expected Behavior

File explorer should work. 

### Debug Information

```shell
Notepad++ v8.8.3   (64-bit)
Build time : Jul  9 2025 - 01:39:59
Scintilla/Lexilla included : 5.5.7/5.4.5
Boost Regex included : 1_85
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
Periodic Backup : ON
Placeholders : OFF
Scintilla Rendering Mode : SC_TECHNOLOGY_DIRECTWRITE (1)
Multi-instance Mode : monoInst
File Status Auto-Detection : cdEnabledNew (for current file/tab only)
Dark Mode : ON
Display Info : 
    primary monitor: 2560x1440, scaling 100%
    visible monitors count: 2
    installed Display Class adapters: 
        0000: Description - Intel(R) UHD Graphics 770
        0000: DriverVersion - 32.0.101.6737
        0001: Description - SudoMaker Virtual Display Adapter
        0001: DriverVersion - 1.10.9.289
        0002: Description - NVIDIA GeForce RTX 5080
        0002: DriverVersion - 32.0.15.8115
OS Name : Windows 11 Pro (64-bit)
OS Version : 24H2
OS Build : 26100.4946
Current ANSI codepage : 1252
Plugins : 
    ComparePlugin (2.0.2)
    mimeTools (3.1)
    NppConverter (4.6)
    NppExport (0.4)
```

**Comment by alankilborn** [comment]
"Steps to Reproduce" need to reference Notepad++ in some way.

**Comment by xomx** [comment]
> https://www.reddit.com/r/WindowsHelp/comments/1m46cmp/cant_click_on_anything_in_file_explorer/

There is [mentioned](https://www.reddit.com/r/WindowsHelp/comments/1m46cmp/comment/n82f1wv/):
`I also noticed that when it is working, bringing-up a right-click context menu bounces back-and-forth between the legacy "more options" menu and the newer, shorter context menu that was introduced with Windows 11. `

Which corresponds to this "alternating new/classic" shell issue reported: #16923

Unfortunately, I'm still not being able to reproduce such shell issues on my comps. There has to be other influencing co-factor.

**Comment by djc5166** [comment]
https://www.elevenforum.com/t/file-explorer-stops-registering-clicks-w11-context-menu-issues.36233/

I had the same issues, documented them here.

Manually un-registering the context menu extension (NppShell.dll) fixed all the issues I was having, so something weird going on there.

**Comment by xomx** [comment]
@djc5166 
I see that you also used custom [Stardock Start11](https://www.stardock.com/products/start11/) StartMenu.
Others mentioned that it was connected to Nvidia's Desktop context menu.
I also see that many manipulated somehow with the Registry before (e.g. to get the old Classic pre-Win11 context menu back).

Since I cannot reproduce such issues on my Win11 comps with NppShell installed, I conclude that it could be some Registry corruption. It is supported also by the fact that for some users it fixes itself after a big MS Win11 update (a Registry repair or the relevant context shell records rewriting back to the vanilla Win11 ones?).

**Comment by djc5166** [comment]
@xomx 
Yea I have start11. But I also saw this on 3 separate machines that I clean installed 24H2 on before they ever touched start11. Also removing the nvidia menu didn't end up making a difference, at least for me.

**Comment by xomx** [comment]
@djc5166 
Ok, I'll try again in a fresh Win11 VM when find a time.
Meanwhile, what N++ version you used (uninstalled)?

**Comment by djc5166** [comment]
I know one machine was v8.6.9 and on 23H2, I keep things on that machine pretty static so its lagging behind. The other two were probably running v8.8 or v8.8.1 (Just going by the time-frame) and 24H2. But I've been encountering this issue on 23H2 and 24H2 for every version at least going back to that v8.6.9. Even as we speak, I just tried to manually re-register the dll on v8.8.5 and 25H2 and the issue immediately comes back, although this one is not a clean install, has start11, etc.

**Comment by xomx** [comment]
Sorry, no, I can't reproduce such issues at all.

I tried on these virtual machines with Win11:
- 22H2 (MS WinDevEval VM images, builds 22621.2715 and 22621.3296)
- 24H2 (26100.1742 - fresh VM installation from downloaded MS ISO - all tests ok, then also let the WU to update it to the latest build 26100.6584 and testing repeated - all ok)

Tried N++ v8.6, v8.8.3 and the latest v8.8.5.

**Comment by djc5166** [comment]
I'll setup a VM this weekend and see if I see the same thing.

It is definitely intermittent.

**Comment by nem1989** [comment]
In addition to the above, this might help diagnose the issue.
I'm having the same issue. This problem goes hand in hand with another unusual behavior when the Notepad++ shell extension is installed. It is easily reproducible on my PC (Windows 11 24H2 build 26100.6584).

1. Install Notepad++ and register the shell extension using the installer.
2. Open File Explorer on any folder.
3. Sequentially right-click on any files several times. While NPP shell extension is installed, the standard Windows 11 context menu will alternate with the classic context menu.
- That is: first click — modern context menu,
- second click — classic menu,
- third click — modern context menu again,
- fourth click — classic again,
- and so on.
4. Uninstall Notepad++ along with the shell extension.
5. The alternating behavior of the context menu no longer occurs - always modern context menu as expected.
6. Reinstall Notepad++ with shell extension.
7. The issue reappears.

Fixing this one might also fix explorer unclickability.

**Comment by djc5166** [comment]
I've managed to reproduce the flip-flop of the context menu within my VM. Still working on seeing if I can get file explorer to stop responding to mouse clicks.

**Comment by mibby** [comment]
Interesting because I reported the same behavior and it was marked as not a bug. @donho 
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/16923
https://old.reddit.com/r/WindowsHelp/comments/1m46cmp/cant_click_on_anything_in_file_explorer/ncjaeei/

**Comment by Wagnard** [comment]
I encountered this “old-new context menu” issue on my computer. A reliable way to reproduce it is: after using **Remote Desktop (MSTSC)**, on the main machine (not the remote one), right-clicking desktop icons alternates between the new Windows 11 context menu and the legacy menu, while right-clicking empty desktop space works normally.

Uninstalling Notepad++ fixes the issue (also removing its context menu entry), so it’s likely caused by something wrong with its context menu DLL.
So for me the trigger is using MSTSC.

N++ debug info :

```
Notepad++ v8.8.5   (64-bit)
Build time: Aug 14 2025 - 00:32:39
Scintilla/Lexilla included: 5.5.7/5.4.5
Boost Regex included: 1_85
Path: C:\Program Files\Notepad++\notepad++.exe
Command Line: 
Admin mode: OFF
Local Conf mode: OFF
Cloud Config: OFF
Periodic Backup: ON
Placeholders: OFF
Scintilla Rendering Mode: SC_TECHNOLOGY_DIRECTWRITE (1)
Multi-instance Mode: monoInst
asNotepad: OFF
File Status Auto-Detection: cdEnabledNew (for current file/tab only)
Dark Mode: OFF
Display Info:
    primary monitor: 2560x1440, scaling 100%
    visible monitors count: 1
    installed Display Class adapters: 
        0000: Description - NVIDIA GeForce RTX 5070
        0000: DriverVersion - 32.0.15.8129
OS Name: Windows 11 Pro (64-bit)
OS Version: 24H2
OS Build: 26100.6584
Current ANSI codepage: 1252
Plugins: 
    mimeTools (3.1)
    NppConverter (4.6)
    NppExport (0.4)
```

**Comment by xomx** [comment]
@Wagnard 
Could you update your post with the N++ `menu > ? > Debug Info...` ?
I don't have a time for another testing right now but I see in the OP DebugInfo this:

> 0001: Description - SudoMaker Virtual Display Adapter

and I'm wondering if it cannot be the real culprit (streaming/remote desktop with such a virtual display).

**Comment by Sammmy1036** [comment]
Running the below command in CMD as Administrator did fix the issue for me: 

regsvr32 /u "C:\Program Files\Notepad++\contextMenu\NppShell.dll"

So something to do with how Notepad++ ties into the context menu.

**Comment by djc5166** [comment]
I haven't really seen the un-clickable explorer windows in awhile, not sure if it was before or after 25H2. The alternating context-menu still happens all the time though.

**Comment by majima-everywhere** [comment]
- My issue: File Explorer windows stop registering mouse clicks (left/right), though keyboard navigation and typing in the address bar still work => Opening a new window resolves the issue but can happen again. + Context menu alternates between old and new versions or behaves inconsistently.
This started happening the very same day I installed Notepad++ and disappears after uninstalling it.
I have Win 11 Pro 24H2 Build 26100.6899

- Cause: After testing, it appears that NppShell.dll (Notepad++ context menu shell extension) is responsible

- My workaround : 
Reinstalling without the “Add Notepad++ to Explorer context menu” option also works

**Comment by anthonyleestark** [comment]
@xomx 
I’ve got this issue as well on Windows 11 24H2 (on one of my PCs).
Sometimes, when I open a file using the “Edit with Notepad++” context menu option, Notepad++ launches normally, but when I return to File Explorer, the main view becomes unresponsive. The address bar still works, I then have to copy the path, close the tab, and open a new one.
However, this happens kind of randomly — there are no specific steps to reproduce it.

Not even sure if this is a bug with Notepad++ or with Windows itself.

**Comment by xomx** [comment]
@anthonyleestark 
> I’ve got this issue as well on Windows 11 24H2 (on one of my PCs).

Lucky you :wink:, I haven't been able to reproduce this problem anywhere yet.
Nowadays I am short on time but hope I post here a testing NppShell.dll debug version with some potential fixes and extended logging soon.

**Comment by djc5166** [comment]
There are 2 notes in the latest windows update preview that sound similar.

https://support.microsoft.com/en-us/topic/october-28-2025-kb5067036-os-builds-26200-7019-and-26100-7019-preview-ec3da7dc-63ba-4b1d-ac41-cf2494d2123a

<img width="973" height="828" alt="Image" src="https://github.com/user-attachments/assets/13129b07-3c9e-4ebc-8482-941b7141db6f" />

Not sure if those have anything to do with what's being discussed here. Haven't been able to try this update yet.

**Comment by djc5166** [comment]
I haven't seen either of these issues again after installing this preview update in 25H2. Signs looking good that it is fixed from the windows side. Must have been some strange interaction, nothing else I have adding to the context menu caused it.

**Comment by mibby** [comment]
Context menu switching still happens for me on 25H2 26220.7051 with Notepad++ 8.8.7 NppShell installed.

**Comment by Wagnard** [comment]
> Context menu switching still happens for me on 25H2 26220.7051 with Notepad++ 8.8.7 NppShell installed.

Probably because it's a gradual rollout fix.
Microsoft will enable it soon. Or you can force the enablement with the vivetool.

**Comment by xomx** [comment]
> I post here a testing NppShell.dll debug version with some potential fixes and extended logging soon.

[NppShell-debug-x64.zip](https://github.com/user-attachments/files/23347260/NppShell-debug-x64.zip)

Now, I really hope that the above Windows update will really fix all the problems reported here. But if not, those of you currently having trouble with the NppShell extension - could you download the above debug version and do the following with it:

1. You must have the NppShell already registered 1st, so if you've already uninstalled it, please reinstall N++ or manually re-register via the `regsvr32 NppShell.dll`. (The posted debug version NppShell.dll in the zip isn't digitally signed and thus cannot be used for such a sparse package shell extension registration...)
2. Go to your installed NppShell.dll folder (probably the `C:\Program Files\Notepad++\contextMenu\` folder.
3. Rename the original existing `NppShell.dll` there to e.g. `NppShell.dll.ori`.
4. Copy there the debug NppShell.dll version from the zip above.
5. For surety logoff/logon back. (This will release potentially loaded original NppShell.dll from the Explorer shell process.)
6. The debug-version has hard-coded logging ON, so you don't have to enable the usual NppShell logging.
7. Now try to invoke the `Edit in Notepad++` context menu as usual with all the problems reported here.
8. Then go to your `C:\Users\[USERLOGIN]\AppData\Roaming\NppShell\` folder and collect there `NppShell.log` created.
9. If that log is short, post it here like:
```
2025-11-04 22:27:56 - PID/TID: 8668/15352 - RegistryKey::ctor: Opened sub key: SOFTWARE\Microsoft\Windows NT\CurrentVersion
2025-11-04 22:27:56 - PID/TID: 8668/15352 - ClassicEditWithNppExplorerCommandHandler::ctor: Creating object
2025-11-04 22:27:56 - PID/TID: 8668/10068 - ClassicEditWithNppExplorerCommandHandler::ctor: Creating object
2025-11-04 22:27:56 - PID/TID: 8668/10068 - SharedState::GetState: Get shared state by caller: ClassicEditWithNppExplorerCommandHandler
2025-11-04 22:27:56 - PID/TID: 8668/10068 - SharedState::SetState: Set shared state to: 0 by caller: ClassicEditWithNppExplorerCommandHandler
2025-11-04 22:27:56 - PID/TID: 8668/10068 - ClassicEditWithNppExplorerCommandHandler::State: Current state: 0
2025-11-04 22:27:57 - PID/TID: 8668/10068 - ClassicEditWithNppExplorerCommandHandler::~tor: Destroying object

2025-11-04 22:27:57 - PID/TID: 9016/6860 - ModernEditWithNppExplorerCommandHandler::ctor: Creating object
2025-11-04 22:27:57 - PID/TID: 9016/16120 - SharedState::SetState: Set shared state to: 1 by caller: ModernEditWithNppExplorerCommandHandler
2025-11-04 22:27:57 - PID/TID: 9016/16120 - SharedState::GetState: Get shared state by caller: ModernEditWithNppExplorerCommandHandler
2025-11-04 22:27:57 - PID/TID: 9016/16120 - ModernEditWithNppExplorerCommandHandler::State: Current state: 1
2025-11-04 22:27:59 - PID/TID: 8668/15352 - ClassicEditWithNppExplorerCommandHandler::~tor: Destroying object
2025-11-04 22:27:59 - PID/TID: 9016/16120 - ModernEditWithNppExplorerCommandHandler::~tor: Destroying object
```
10. If it's long, zip it and attach to your post here.
11. At the end, don't forget to reverse the step No. 3.

**Comment by djc5166** [comment]
One of my machines I reformatted and clean installed the 25h2 release, It had the 2 issues, even after the updates.

I was leaning back to it not being fixed, but maybe it actually is due to the 'gradual rollout'.

The first machine still seems ok, but maybe I just haven't run into it yet.

I'll try your debug version.

**Comment by djc5166** [comment]
[NppShell.zip](https://github.com/user-attachments/files/23554977/NppShell.zip)

Here is a couple iterations of the context menu flipping back and forth.

**Comment by Wagnard** [comment]
@xomx 
Here is is.
To repro, I MSTSC in one of my other machine, did a right click on an icon there a few time for making the context menu appear  (no npp on that machine, so no issue there),then I signed off of that remote machine, then the bug was present on main machine.

```
2025-11-15 20:08:56 - PID/TID: 15072/19772 - RegistryKey::ctor: Opened sub key: SOFTWARE\Microsoft\Windows NT\CurrentVersion
2025-11-15 20:08:56 - PID/TID: 15072/19772 - ClassicEditWithNppExplorerCommandHandler::ctor: Creating object
2025-11-15 20:08:56 - PID/TID: 15072/10520 - ClassicEditWithNppExplorerCommandHandler::ctor: Creating object
2025-11-15 20:08:56 - PID/TID: 15072/10520 - SharedState::GetState: Get shared state by caller: ClassicEditWithNppExplorerCommandHandler
2025-11-15 20:08:56 - PID/TID: 15072/10520 - SharedState::SetState: Set shared state to: 0 by caller: ClassicEditWithNppExplorerCommandHandler
2025-11-15 20:08:56 - PID/TID: 15072/10520 - ClassicEditWithNppExplorerCommandHandler::State: Current state: 0
2025-11-15 20:08:56 - PID/TID: 15072/10520 - ClassicEditWithNppExplorerCommandHandler::~tor: Destroying object

2025-11-15 20:08:57 - PID/TID: 20892/7820 - ModernEditWithNppExplorerCommandHandler::ctor: Creating object
2025-11-15 20:08:57 - PID/TID: 20892/26052 - SharedState::SetState: Set shared state to: 1 by caller: ModernEditWithNppExplorerCommandHandler
2025-11-15 20:08:57 - PID/TID: 20892/26052 - SharedState::GetState: Get shared state by caller: ModernEditWithNppExplorerCommandHandler
2025-11-15 20:08:57 - PID/TID: 20892/26052 - ModernEditWithNppExplorerCommandHandler::State: Current state: 1
2025-11-15 20:08:58 - PID/TID: 15072/19772 - ClassicEditWithNppExplorerCommandHandler::~tor: Destroying object
2025-11-15 20:08:58 - PID/TID: 20892/26052 - ModernEditWithNppExplorerCommandHandler::~tor: Destroying object
2025-11-15 20:08:58 - PID/TID: 15072/19772 - ClassicEditWithNppExplorerCommandHandler::ctor: Creating object
2025-11-15 20:08:58 - PID/TID: 15072/10520 - ClassicEditWithNppExplorerCommandHandler::ctor: Creating object
2025-11-15 20:08:58 - PID/TID: 15072/10520 - SharedState::GetState: Get shared state by caller: ClassicEditWithNppExplorerCommandHandler
2025-11-15 20:08:58 - PID/TID: 15072/10520 - SharedState::SetState: Set shared state to: 0 by caller: ClassicEditWithNppExplorerCommandHandler
2025-11-15 20:08:58 - PID/TID: 15072/10520 - ClassicEditWithNppExplorerCommandHandler::State: Current state: 0
2025-11-15 20:08:58 - PID/TID: 15072/10520 - ClassicEditWithNppExplorerCommandHandler::~tor: Destroying object
2025-11-15 20:08:58 - PID/TID: 20892/7820 - ModernEditWithNppExplorerCommandHandler::ctor: Creating object
2025-11-15 20:08:58 - PID/TID: 20892/26052 - SharedState::SetState: Set shared state to: 1 by caller: ModernEditWithNppExplorerCommandHandler
2025-11-15 20:08:58 - PID/TID: 20892/26052 - SharedState::GetState: Get shared state by caller: ModernEditWithNppExplorerCommandHandler
2025-11-15 20:08:58 - PID/TID: 20892/26052 - ModernEditWithNppExplorerCommandHandler::State: Current state: 1
2025-11-15 20:09:00 - PID/TID: 15072/19772 - ClassicEditWithNppExplorerCommandHandler::~tor: Destroying object
2025-11-15 20:09:00 - PID/TID: 20892/26052 - ModernEditWithNppExplorerCommandHandler::~tor: Destroying object
2025-11-15 20:09:06 - PID/TID: 15072/25556 - ClassicEditWithNppExplorerCommandHandler::ctor: Creating object
2025-11-15 20:09:06 - PID/TID: 15072/25556 - ClassicEditWithNppExplorerCommandHandler::ctor: Creating object
2025-11-15 20:09:06 - PID/TID: 15072/25556 - SharedState::GetState: Get shared state by caller: ClassicEditWithNppExplorerCommandHandler
2025-11-15 20:09:06 - PID/TID: 15072/25556 - SharedState::SetState: Set shared state to: 0 by caller: ClassicEditWithNppExplorerCommandHandler
2025-11-15 20:09:06 - PID/TID: 15072/25556 - ClassicEditWithNppExplorerCommandHandler::State: Current state: 0
2025-11-15 20:09:06 - PID/TID: 15072/25556 - ClassicEditWithNppExplorerCommandHandler::~tor: Destroying object
2025-11-15 20:09:22 - PID/TID: 15072/19772 - ClassicEditWithNppExplorerCommandHandler::ctor: Creating object
2025-11-15 20:09:22 - PID/TID: 15072/4824 - ClassicEditWithNppExplorerCommandHandler::ctor: Creating object
2025-11-15 20:09:22 - PID/TID: 15072/4824 - SharedState::GetState: Get shared state by caller: ClassicEditWithNppExplorerCommandHandler
2025-11-15 20:09:22 - PID/TID: 15072/4824 - SharedState::SetState: Set shared state to: 0 by caller: ClassicEditWithNppExplorerCommandHandler
2025-11-15 20:09:22 - PID/TID: 15072/4824 - ClassicEditWithNppExplorerCommandHandler::State: Current state: 0
2025-11-15 20:09:22 - PID/TID: 15072/4824 - ClassicEditWithNppExplorerCommandHandler::~tor: Destroying object

2025-11-15 20:09:23 - PID/TID: 19000/5116 - ModernEditWithNppExplorerCommandHandler::ctor: Creating object
2025-11-15 20:09:23 - PID/TID: 19000/12356 - SharedState::SetState: Set shared state to: 1 by caller: ModernEditWithNppExplorerCommandHandler
2025-11-15 20:09:23 - PID/TID: 19000/12356 - SharedState::GetState: Get shared state by caller: ModernEditWithNppExplorerCommandHandler
2025-11-15 20:09:23 - PID/TID: 19000/12356 - ModernEditWithNppExplorerCommandHandler::State: Current state: 1
2025-11-15 20:09:24 - PID/TID: 15072/19772 - ClassicEditWithNppExplorerCommandHandler::~tor: Destroying object
2025-11-15 20:09:24 - PID/TID: 19000/12356 - ModernEditWithNppExplorerCommandHandler::~tor: Destroying object
2025-11-15 20:09:24 - PID/TID: 15072/19772 - ClassicEditWithNppExplorerCommandHandler::ctor: Creating object
2025-11-15 20:09:24 - PID/TID: 15072/4824 - ClassicEditWithNppExplorerCommandHandler::ctor: Creating object
2025-11-15 20:09:24 - PID/TID: 15072/4824 - SharedState::GetState: Get shared state by caller: ClassicEditWithNppExplorerCommandHandler
2025-11-15 20:09:24 - PID/TID: 15072/4824 - SharedState::SetState: Set shared state to: 0 by caller: ClassicEditWithNppExplorerCommandHandler
2025-11-15 20:09:24 - PID/TID: 15072/4824 - ClassicEditWithNppExplorerCommandHandler::State: Current state: 1
2025-11-15 20:09:24 - PID/TID: 15072/4824 - ClassicEditWithNppExplorerCommandHandler::~tor: Destroying object
2025-11-15 20:09:24 - PID/TID: 19000/5116 - ModernEditWithNppExplorerCommandHandler::ctor: Creating object
2025-11-15 20:09:24 - PID/TID: 15072/19772 - ClassicEditWithNppExplorerCommandHandler::ctor: Creating object
2025-11-15 20:09:24 - PID/TID: 19000/12356 - SharedState::SetState: Set shared state to: 1 by caller: ModernEditWithNppExplorerCommandHandler
2025-11-15 20:09:24 - PID/TID: 19000/12356 - SharedState::GetState: Get shared state by caller: ModernEditWithNppExplorerCommandHandler
2025-11-15 20:09:24 - PID/TID: 19000/12356 - ModernEditWithNppExplorerCommandHandler::State: Current state: 1
2025-11-15 20:09:24 - PID/TID: 15072/12148 - ClassicEditWithNppExplorerCommandHandler::ctor: Creating object
2025-11-15 20:09:24 - PID/TID: 15072/12148 - SharedState::GetState: Get shared state by caller: ClassicEditWithNppExplorerCommandHandler
2025-11-15 20:09:24 - PID/TID: 15072/12148 - SharedState::SetState: Set shared state to: 0 by caller: ClassicEditWithNppExplorerCommandHandler
2025-11-15 20:09:24 - PID/TID: 15072/12148 - ClassicEditWithNppExplorerCommandHandler::State: Current state: 1
2025-11-15 20:09:24 - PID/TID: 15072/12148 - ClassicEditWithNppExplorerCommandHandler::~tor: Destroying object
2025-11-15 20:09:26 - PID/TID: 19000/12356 - ModernEditWithNppExplorerCommandHandler::~tor: Destroying object
2025-11-15 20:09:26 - PID/TID: 15072/19772 - ClassicEditWithNppExplorerCommandHandler::~tor: Destroying object
2025-11-15 20:09:26 - PID/TID: 15072/19772 - ClassicEditWithNppExplorerCommandHandler::~tor: Destroying object
2025-11-15 20:09:27 - PID/TID: 15072/19772 - ClassicEditWithNppExplorerCommandHandler::ctor: Creating object
2025-11-15 20:09:27 - PID/TID: 15072/4824 - ClassicEditWithNppExplorerCommandHandler::ctor: Creating object
2025-11-15 20:09:27 - PID/TID: 15072/4824 - SharedState::GetState: Get shared state by caller: ClassicEditWithNppExplorerCommandHandler
2025-11-15 20:09:27 - PID/TID: 15072/4824 - SharedState::SetState: Set shared state to: 0 by caller: ClassicEditWithNppExplorerCommandHandler
2025-11-15 20:09:27 - PID/TID: 15072/4824 - ClassicEditWithNppExplorerCommandHandler::State: Current state: 0
2025-11-15 20:09:27 - PID/TID: 15072/4824 - ClassicEditWithNppExplorerCommandHandler::~tor: Destroying object
2025-11-15 20:09:27 - PID/TID: 19000/5116 - ModernEditWithNppExplorerCommandHandler::ctor: Creating object
2025-11-15 20:09:27 - PID/TID: 19000/12356 - SharedState::SetState: Set shared state to: 1 by caller: ModernEditWithNppExplorerCommandHandler
2025-11-15 20:09:27 - PID/TID: 19000/12356 - SharedState::GetState: Get shared state by caller: ModernEditWithNppExplorerCommandHandler
2025-11-15 20:09:27 - PID/TID: 19000/12356 - ModernEditWithNppExplorerCommandHandler::State: Current state: 1
2025-11-15 20:09:28 - PID/TID: 15072/19772 - ClassicEditWithNppExplorerCommandHandler::~tor: Destroying object
2025-11-15 20:09:28 - PID/TID: 19000/12356 - ModernEditWithNppExplorerCommandHandler::~tor: Destroying object
```

**Comment by Wagnard** [comment]
@xomx 
On my end I was able to fix this by removing the "SharedSate" stuff and by not registering the old context menu on windows 11 :

```
const EXPCMDSTATE ClassicEditWithNppExplorerCommandHandler::State(IShellItemArray* psiItemArray)
{
    UNREFERENCED_PARAMETER(psiItemArray);

    return ECS_ENABLED;
}

const EXPCMDSTATE ModernEditWithNppExplorerCommandHandler::State(IShellItemArray* psiItemArray)
{
    UNREFERENCED_PARAMETER(psiItemArray);

    return ECS_ENABLED;
}


HRESULT NppShell::Installer::Install()
{
    const bool isWindows11 = IsWindows11Installation();

    HRESULT result = S_OK;

    // Clean up the 8.5 Windows 11 hack if present.
    CleanupHack();

    if (isWindows11)
    {
        // We need to unregister the old menu on Windows 11 to prevent double entries in the old menu.
        UnregisterOldContextMenu();

        // To register the sparse package, we need to do it on another thread due to WinRT requirements.
        thread reRegisterThread(ReRegisterSparsePackage);
        reRegisterThread.join();
    }
	else
	{
		result = RegisterOldContextMenu();
	}
    // Ensure we schedule old files for removal on next reboot.
    MoveFileToTempAndScheduleDeletion(GetApplicationPath() + L"\\NppShell_01.dll", false);
    MoveFileToTempAndScheduleDeletion(GetApplicationPath() + L"\\NppShell_02.dll", false);
    MoveFileToTempAndScheduleDeletion(GetApplicationPath() + L"\\NppShell_03.dll", false);
    MoveFileToTempAndScheduleDeletion(GetApplicationPath() + L"\\NppShell_04.dll", false);
    MoveFileToTempAndScheduleDeletion(GetApplicationPath() + L"\\NppShell_05.dll", false);
    MoveFileToTempAndScheduleDeletion(GetApplicationPath() + L"\\NppShell_06.dll", false);

    // This include the old NppModernShell and NppShell files from the main program directory.
    MoveFileToTempAndScheduleDeletion(GetApplicationPath() + L"\\NppShell.dll", false);
    MoveFileToTempAndScheduleDeletion(GetApplicationPath() + L"\\NppShell.msix", false);
    MoveFileToTempAndScheduleDeletion(GetApplicationPath() + L"\\NppModernShell.dll", false);
    MoveFileToTempAndScheduleDeletion(GetApplicationPath() + L"\\NppModernShell.msix", false);

    // Finally we notify the shell that we have made changes, so it refreshes the context menus.
    SHChangeNotify(SHCNE_ASSOCCHANGED, SHCNF_IDLIST, 0, 0);

    return result;
}
```

After that, no more issues, "edit with notepad++" still appear in both menu as it should and there is no random swapping between new and old context menu.

**Comment by xomx** [comment]
@Wagnard 

> not registering the old context menu on windows 11

Of course, this will fix the changing context-menu issue but then the old ctx-menu will not be available at all for the SW, which doesn't use the new Win11 ctx-API (e.g. I use such a file manager...). The right question is why some of the users experience this problem while others (majority I think) not.

**Comment by Wagnard** [comment]
> [@Wagnard](https://github.com/Wagnard)
> 
> > not registering the old context menu on windows 11
> 
> Of course, this will fix the changing context-menu issue but then the old ctx-menu will not be available at all for the SW, which doesn't use the new Win11 ctx-API (e.g. I use such a file manager...). The right question is why some of the users experience this problem while others (majority I think) not.

That make sense.
The issue seems to be that the "ShareState" is unreliable for whatever reason (probably because it could be called from different / multiple processes).

**Comment by mibby** [comment]
Still no official fix for the context menu switching with nppshell registered?

**Comment by nem1989** [comment]
> [@xomx](https://github.com/xomx) On my end I was able to fix this by removing the "SharedSate" stuff and by not registering the old context menu on windows 11 :
> 
> const EXPCMDSTATE ClassicEditWithNppExplorerCommandHandler::State(IShellItemArray* psiItemArray)
...
> 
> After that, no more issues, "edit with notepad++" still appear in both menu as it should and there is no random swapping between new and old context menu.

Why not atleast implement this fix as an optional feature during installation? Looks fine to me. Currently, I have to either suffer with this bug or remove the context menu entry completely. 

> [@Wagnard](https://github.com/Wagnard)
> 
> > not registering the old context menu on windows 11
> 
> Of course, this will fix the changing context-menu issue but then the old ctx-menu will not be available at all for the SW, which doesn't use the new Win11 ctx-API (e.g. I use such a file manager...). The right question is why some of the users experience this problem while others (majority I think) not.

I suspect many users run into this issue but don’t realize Notepad++ is the cause. I didn’t notice the behavior myself for quite a while, and once I did, it took a lot of digging to figure out that Notepad++ was responsible.

**Comment by Wagnard** [comment]
Here is a workaround for those who are comfortable with the registry:

```
1- Go to HKEY_CLASSES_ROOT\*\shell\ANotepad++64 and note the value of ExplorerCommandHandler.

2- Search the registry for that value.

3- You should find it here: HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{Your value}

4- Delete the key HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{Your value}

5- Delete the key HKEY_CLASSES_ROOT\*\shell\ANotepad++64

6- Reboot and enjoy.
```

**Comment by pferrucci** [comment]
I can confirm this issue on all Windows Server 2025 (equivalent to Win11).
We install Notepad++ on all servers for our customers.
