### ISSUE TITLE
Window returns to incorrect location on tab change with long lines and wordwrap mode enabled

### ISSUE THREAD

**Issue by PH0lder** [notepad-plus-plus/notepad-plus-plus#2576]
### Description of the Issue
WIndow returns to incorrect location on tab change with long lines and wordwrap mode enabled.

I have View | Word Wrap enabled, and a few lines that are longer than the width of the window (i.e. are wrapped.)  When I switch to another editor tab and then come back, the cursor stays on the correct line, but sometimes it's not actually visible in the window because it is scrolled to the wrong place.  I assume it's not counting the line number correctly when there are long wrapped lines.

### Steps to Reproduce the Issue
1.  Have long lines that need word wrapping in a long document.
2.  Enable View | Word Wrap.
3.  Scroll to the bottom of the document.
4, Switch to another editing tab.
5. Switch back to the first tab with the long word wrapped document.

### Expected Behavior
When I come back to the window after switching tabs, the window should have stayed in the same state (location and scrolled to position) it was before I switched tabs.

### Actual Behavior
The cursor remains in the correct location, but the location moves, including not even being visible on screen.

### Debug Information
Notepad++ v7.2   (64-bit)
Build time : Nov  2 2016 - 11:27:56
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10
Plugins : mimeTools.dll NppConverter.dll 

This has occurred in older versions for some time, including in the 32bit version before I upgraded to the 64bit version.

**Comment by ysrn** [comment]
Please fix this, it's making it impossible to work with word-wrapped files.

**Comment by NicolBolas** [comment]
Is there any movement on this issue? Any at all? Is this a Scintella problem or a Nodepad++ problem?

**Comment by fml2** [comment]
This issue is probably related to #3570.

**Comment by zhuhang** [comment]
Any updates on this issue?

**Comment by fml2** [comment]
Yes, this is better now but still not quite well. If the cursor is at the end of the file in an empty line (i.e. the last text line has a CR at the end), then, after switching the tab to another file and back, the cursor is still o the right line, but it is barely visible. The file got scrolled one line up.

The file has 2792 lines, the last one is empty.

**Comment by sasumner** [comment]
@fml2 
Can you post a before and after screenshot of this?

**Comment by fml2** [comment]
Sorry, I can't post screenshots with the old version of NP++ since I already deleted it. But I can post some imags with NP++ 7.5.9 (the latest version as of now).

Before I do that, I must say that I can't reproduce the behaviour with an arbitrary file. It shows so far on one particular file only (but is reproducible with it).

Also, after some experiments, I don't think it has to do with tab switching but rather just with cursor navigation within a file. I.e. I don't have to switch tabs in order to reproduce the behaviour (this might mean that it should be a subject for a new issue).

Anyway, here are the images:

1. After pressing Ctrl+Home, the cursor is at the top left position -- as axpected:

![issue-1](https://user-images.githubusercontent.com/534392/47045234-9d57af80-d192-11e8-8200-df0928de4b18.png)

2. After pressing Ctrl+End, the cusrsor is on the last line, but it is not fully visible, only some top pixels of it (see the red frame, made by me):

![issue-2](https://user-images.githubusercontent.com/534392/47045296-c5dfa980-d192-11e8-9e29-a51ce1ca71ba.png)

3. After pressing Ctrl+Home again, the last line is fully visible:

![issue-3](https://user-images.githubusercontent.com/534392/47045353-e3147800-d192-11e8-8ec5-b538864e18f1.png)

**Comment by rel91** [comment]
I think that this issue has reared its head again. I'm running the latest version and it seems to be happening again.

Debug Info:
Notepad++ v7.7.1   (64-bit)
Build time : Jun 16 2019 - 21:24:47
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : mimeTools.dll NppConverter.dll

**Comment by cmeriaux** [comment]
I've fixed this problem but the Fix introduce a performance regression. So the fix was reverted ! Sorry

**Comment by PH0lder** [comment]
Unfortunately this has returned in fully annoying fashion.  Maybe I am a rare breed who uses lots of word wrapped files, but it sure is annoying to me... So I'm going to reopen this and hope for a new fix...

**Comment by qiexia** [comment]
wow is this on the nose.  7.5.9 fixes, 7.6 immediately breaks again, and still broken to this day.
