### ISSUE TITLE
Can't save files that are empty when opening

### ISSUE THREAD

**Issue by schtandard** [notepad-plus-plus/notepad-plus-plus#3283]
### Description of the Issue
When I open an empty text file, type some text into it and try saving it I get the error message "The file cannot be saved and it may be protected. Do you want to launch Notepad++ in Administrator mode?". Upon affirming this and trying again, I instead get the error message "Failed to save file. Not enough space on disk to save file?".

After editing the same file with another program and opening the now non-empty file with Notepad++, it is handled just fine.

### Steps to Reproduce the Issue

1. Create an empty text file. Can be done with Notepad++, but has to be closed afterwards.
2. Open the empty file with Notepad++.
3. Type something.
4. Try saving it.

### Debug Information
I have a fresh install of Notepad++ on Windows 10:

Notepad++ v7.4   (32-bit)
Build time : May 14 2017 - 20:35:30
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : mimeTools.dll NppConverter.dll NppExport.dll PluginManager.dll

**Comment by AngryGamer** [comment]
Dupe #3272

**Comment by Eolia** [comment]
Hi

Solved in 7.4.1^^

**Comment by aapmeid** [comment]
2 days ago I suddenly started having this problem. I just installed 7.5.1 in order to hopefully solve issue --> still occurring :(

Help?

**Comment by aalrikabi** [comment]
i am having the same problem using notpad++ with winscap . i had to close all the document in notepad and reopen my document.

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.
