### ISSUE TITLE
New translation updated

### ISSUE THREAD

**Issue by donho** [notepad-plus-plus/notepad-plus-plus#4286]
A major updated translation is available here:
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/installer/nativeLang/english.xml

You can use the following html file to identify the change easier:
[7.5_vs_7.5.5.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/1799862/7.5_vs_7.5.5.zip)

**Comment by MAPJe71** [comment]
Typos:
1. `DroppingFolderAsProjetModeWarning` --> `DroppingFolderAsProjectModeWarning` in [line 974](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/fab3db50dfe68f2e94b5870e9d4af8d4bff751cd/PowerEditor/installer/nativeLang/english.xml#L974)
2. `FileTooBigToOpene` --> `FileTooBigToOpen` in [line 1001](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/fab3db50dfe68f2e94b5870e9d4af8d4bff751cd/PowerEditor/installer/nativeLang/english.xml#L1001)

**Comment by batagy** [comment]
Hi!

1. The right click menu in Shortcut Mapper is not yet available. This 3 items:

> Modify
> Delete
> Clear

2. FindInFinder section translation is not picked by program (version 7.5.5). Below section , even if translated, but appears still in English:

```
     <FindInFinder title="Find in finder">
         <Item id="1"    name="Find All"/>
         <Item id="2"    name="Close"/>
         <Item id="1711" name="Find what:"/>
         <Item id="1713" name="Search only in found lines"/>
         <Item id="1714" name="Match &amp;whole word only"/>
         <Item id="1715" name="Match &amp;case"/>
         <Item id="1716" name="Search mode"/>
         <Item id="1717" name="Normal"/>
         <Item id="1719" name="Regular &amp;expression"/>
         <Item id="1718" name="Extended (\n, \r, \t, \0, \x...)"/>
         <Item id="1720" name="&amp;. matches newline"/>
     </FindInFinder>
```

3. Where below section is appearing in program?

```
<WindowsDlg>
     <ColumnName name="Name"/>
     <ColumnPath name="Path"/>
     <ColumnType name="Type"/>
 </WindowsDlg>
```

4. The Incremental Search Window would be nice to be translatable too. It’s still not translatable.

**Comment by batagy** [comment]
Hi!

2) is fixed in version 7.5.6.
3) This appears in Windows dialog, in Windows menu.

**Comment by ArkadiuszMichalski** [comment]
@donho This bug still needed?

**Comment by ArkadiuszMichalski** [comment]
@donho From https://github.com/notepad-plus-plus/notepad-plus-plus/issues/4286#issuecomment-373694641 still missing 1. and 4., so maybe still keep it open?

**Comment by donho** [comment]
@ArkadiuszMichalski 
It would be the other issues, if users wanna open them.

**Comment by Lidgeu** [comment]
Hi Donho,

I'am using Notepad++ (32bit) since years. I recently updated to 8.4.2 ... and noticed that the here below texts are still untranslatable (missing in your English language master XML).
I should be nice to have the master updated to enable localisations :o)

![TranslationMissing-1](https://user-images.githubusercontent.com/88983709/172059769-43dcd5af-2466-443d-85ed-e267b8ed775f.jpg)
![TranslationMissing-2](https://user-images.githubusercontent.com/88983709/172059766-d47bc4b7-b194-4dc9-80ec-167c21e6132e.jpg)
![TranslationMissing-3](https://user-images.githubusercontent.com/88983709/172059767-f267ce33-3a8f-41fe-a51b-b680b6f22ba7.jpg)

I understand that it could be more "complex" for the plugins. _DSpellCheck_ and _NppExport_, are "brand names"  but the others should be translated ;o)

Many thanks before hand.

**Comment by alankilborn** [comment]
@Lidgeu 

None of the stuff you cite is realistically translatable.

**Comment by Lidgeu** [comment]
@alankilborn 

I don't think so (not only for French, it's true for all the languages).
To avoid overloading this subject, I wrote my comments - and show cases -  in this .pdf

[MissingTranslationsFixing.pdf](https://github.com/notepad-plus-plus/notepad-plus-plus/files/8864966/MissingTranslationsFixing.pdf)

For the best usage of the developers ;o)

**Comment by alankilborn** [comment]
The translation mechanism uses "ID values" to accomplish translation.  Open english.xml (or french.xml) and you will see that everything that is translated has an ID associated with it.

In brief, here are the problems with the items in your screenshots:

* `Trim Trailing and Save` - you can create a macro and give it any name you want.  That macro will not have an ID associated with it, just a name (thus, not translatable).  "Trim Trailing and Save" just happens to be a sample macro distributed with Notepad++

* `Launch in Firefox` and others in second screenshot - similar to macros, these are `Run` menu entries; again, given names; they are not "commands" and thus have no IDs.  And, by the way, a lot of these are not present in recent versions of Notepad++.  Regardless, not realistically translatable.

* Plugins - plugins are dynamic and mostly created by users, not the Notepad++ devs; thus, a bit difficult to hold N++ devs responsible for translating these names.

**Comment by Lidgeu** [comment]
Got it ! :o)

I understand for the plugins. For the others points, "Shortcut mapper"
standard function allows the user to customize them :o).
I did it for my own usage (and it's operational).
Ibidem for the couple of basic plugins I'm using (now, they speak French to
me ;o))

So, I clos here my feefback about "official" translations.

Many thanks for your informations.



Le mer. 8 juin 2022 à 23:08, alankilborn ***@***.***> a
écrit :
