### ISSUE TITLE
Feature Request: Configurable Timeout for File Status Auto-Detection

### ISSUE THREAD

**Issue by gabeluci** [notepad-plus-plus/notepad-plus-plus#4306]
_Short version:_ I'd like to be able to configure the timeout for the file status auto-detection that happens when Notepad++ gets back focus.

_Background:_ Sometimes I will open a file on the network at work and put my laptop to sleep without closing the file. If I open my laptop off of the network later and go back to Notepad++, the whole program freezes while it tries to reach the network share that the file is on. It seems to take about 30 seconds for it to finally give up. And I can't even do anything else during that time, because if I leave Notepad++ and come back after 30 seconds, the whole process starts again.

So I'd like to be able to shorten that timeout. I'd probably set it to something really short, like 2 seconds.

The other option is to maybe do that auto-detection on a background thread so the UI isn't locked up.

**Comment by MetaChuh** [comment]
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

**Comment by gabeluci** [comment]
Awesome, thank you!

**Comment by sasumner** [comment]
@gabeluci I predict this is going to be a short-lived "awesome". ;)

**Comment by gabeluci** [comment]
@sasumner Admittedly I didn't test it :) I saw something in the release notes about the auto-change detection so I thought maybe this was fixed too. But I guess not eh?

**Comment by sasumner** [comment]
@gabeluci Correct, there were some changes in the detection area, but nothing in regards to your timeout request, AFAIK.

**Comment by Haas11** [comment]
Was this really still not addressed? 
It's preventing me from using the app in any reasonable way.

**Comment by xomx** [comment]
Related: #8055

**Comment by donho** [comment]
@gabeluci 
Please try the latest state of fixed binary here (x64):
https://github.com/notepad-plus-plus/notepad-plus-plus/actions/runs/11118197845/artifacts/1998785683

The hanging issue should be improved considerably.

**Comment by gabeluci** [comment]
I gave it a try. It still locks up, but not nearly as long. The first time it was at most 10 seconds, then subsequent times were 3-4 seconds. Much better, thank you!
