### ISSUE TITLE
wrong character set after saving txt file

### ISSUE THREAD

**Issue by nplus-user** [notepad-plus-plus/notepad-plus-plus#431]
When I create a txt file with default win-1251 encoding and open it again after saving sometimes I see text with wrong character set. Notepad++ works under Win7x64 (regional language parameters - russian). This bug was noted a long time ago with many previous versions (or subversions), but now it appears more often. I hope it is solvable problem.
![nplus](https://cloud.githubusercontent.com/assets/13237441/8570581/c4d36aba-259a-11e5-82d9-731abb5e7269.png)

**Comment by milipili** [comment]
Encodings are detected and not written whitin the file. Could you attach a file encoded in win-1251 which is detected in iso-8859-8 ?

**Comment by nplus-user** [comment]
âŕëüöű Isitan R 1270ő68 - 1700 ĺâđî
âŕëüöű Isitan R 1270ő75 - 2000 ĺâđî
1270?68 - 1700 ????
1270?75 - 2000 ????

**Comment by nplus-user** [comment]
Sometimes wrong encoding is Macintosh, sometimes iso-8859-8, maybe something else, I don't remember exactly.

**Comment by nplus-user** [comment]
Is the bug confirmed?

**Comment by nplus-user** [comment]
Some new issues:
1) create new Notepad++ txt file through context menu by right button click
2) status bar shows DOS/Windows ANSI encoding instead default Windows1251
3) type random symbols, save file and close it (do not close N++, just close new created file)
4) look at the status bar again - there is default Windows 1251 encoding of "new 1" file
5) close N++ and open previously saved file - there is DOS/Windows UTF-8 w/o BOM encoding

**Comment by lehha** [comment]
This bug appears when you open a file in windows-1251 sometimes switchs to character set DOS.
May be add to the program settings option specifying a standard encoding?

**Comment by XX-J** [comment]
> Sometimes wrong encoding is Macintosh, sometimes iso-8859-8, maybe something else, I don't remember exactly.

 Confirmed.
![notepad encode bug](https://cloud.githubusercontent.com/assets/17948007/17830829/c525a7ac-66e0-11e6-8761-7ab1580c9eb1.jpg)
[Новый текстовый документ.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/428246/default.txt)

**Comment by igordegraf** [comment]
Confirm the bug. Problem with windows-1251 encoding detection starts from 6.5. 
Behaviour is unstable - depends on file content. Some documents opened as Macintosh, some as Windows 949, some as OEM-8859-8 and so on.

Is someone have information about problem and solution?
Bug become long standing. 
Problem only with windows-1251 ?

=====================
Example shown windows-1251 content. Save to file as windows-1251, close and open. Encoding wil be detected as Windows 949 !?!?!

`<?xml version="1.0" encoding="windows-1251"?>
<ТрансИнф версияФормата="ФНС:1.0" кодТипаДокументооборота="10" типДокументооборота="Документ" кодТипаТранзакции="01" типТранзакции="ДокументНО" идентификаторДокументооборота="6abc8041c5c44420b292763663f4d72e" ВерсПрог="4.0.0.18">
  <отправитель идентификаторСубъекта="4213" типСубъекта="налоговыйОрган" />
  <спецоператор идентификаторСубъекта="1GX" типСубъекта="спецоператор" />
  <получатель идентификаторСубъекта="1GX.4243015398@R42.DATACRYPT.RU" типСубъекта="абонент" />
  <ДопСв>
    <Sfo>
      <ContainerName>FNS_4213_1GX.4243015398@R42.DATACRYPT.RU_2fb89498ecb04854b4764084708f6825_10_01_01.zip</ContainerName>
      <Attribute Name="ИНННП" Value="4243015398" />
      <Attribute Name="КППНП" Value="424301001" />
      <Attribute Name="НаименованиеНП" Value="МУП ЖКУ &quot;БЕЛОГОРСК&quot;" />
    </Sfo>
  </ДопСв>
  <документ кодТипаДокумента="01" типДокумента="документ" типСодержимого="xml" сжат="true" зашифрован="false" идентификаторДокумента="3ee4e1b3cde449639e024e1e8dee0a92" исходноеИмяФайла="ON_INFSOOB_4243015398424301001_4243015398424301001_4213_20180110_9fd46c27-52cf-4da7-8da7-d243b97a9589.xml">
    <содержимое имяФайла="b038f09e3f9a4f8f89d67a4f47d2cfdf.bin" />
    <подпись имяФайла="d8c29c63cc944681a2512cc5fb970d55.bin" роль="налоговыйОрган" />
  </документ>
  <документ кодТипаДокумента="03" типДокумента="приложение" типСодержимого="pdf" сжат="true" зашифрован="false" идентификаторДокумента="a97afe2e623f425b80806c9c5ea48301" исходноеИмяФайла="1165014_4213_4243015398424301001_ba13a533-5d12-425d-aaef-12c6a51d795c_20180109_ba13a533-5d12-425d-aaef-12c6a51d795c.pdf">
    <содержимое имяФайла="84df737aab794a45ab4da8934877d060.bin" />
    <подпись имяФайла="5aac1a64f41d493bbda22400f3ef60ae.bin" роль="налоговыйОрган" />
  </документ>
  <документ кодТипаДокумента="02" типДокумента="описание" типСодержимого="xml" сжат="true" зашифрован="false" идентификаторДокумента="5670bfacc8fc4de4afaea12b8e1e7f17" исходноеИмяФайла="TR_INFSOOB.xml">
    <содержимое имяФайла="4c5da5cae9f7444398e1ac71c6293220.bin" />
  </документ>
  <документ кодТипаДокумента="99" типДокумента="абонентИнфо" типСодержимого="xml" сжат="true" зашифрован="false" идентификаторДокумента="967bd4acfae942f581fddde728251011" исходноеИмяФайла="RELAY_INFO_GNIVC.xml">
    <содержимое имяФайла="ba4075130f494a829802e252e683518a.bin" />
  </документ>
</ТрансИнф>`

**Comment by CookiePLMonster** [comment]
Fixed by #4925

**Comment by XX-J** [comment]
@CookiePLMonster

> Fixed by #4925

 Incompletely. My second example, written above, is not actually fixed:

   [GUW32.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/432498/GUW32.txt)

 Incorrect encoding (EUC-KR):

![n 1](https://user-images.githubusercontent.com/17948007/49260003-aeac0100-f44c-11e8-9b4b-54b174c4d66f.png)

 Correct encoding (OEM):

![n 3](https://user-images.githubusercontent.com/17948007/49260268-eff0e080-f44d-11e8-9cc4-66e87fa86481.png)
_______________________________________________________

   [Support.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/432501/Support.txt)

 Incorrect encoding (EUC-KR):

![n 2](https://user-images.githubusercontent.com/17948007/49260538-1a8f6900-f44f-11e8-9013-9c09e5932214.png)

 Correct encoding (OEM):

![n 4](https://user-images.githubusercontent.com/17948007/49260549-2418d100-f44f-11e8-8be2-2e101a38b43a.png)
_______________________________________________________

 NotepAd++ v7.6 x64; Win7SP1 x64

**Comment by chcg** [comment]
@Geograph-us It is possible to disable to auto detection complete within the settings->preferences..->MISC.-> Autodetect character encoding

**Comment by KJlt77** [comment]
Similar problem with the latest version in the autodetect character set mode.

I think autodetect identifies wrong encoding in cases when some key characters of the encoding are missing in the file.

For example I have a file with a single character "Ė" (0xCB) of Windows-1257. When I open the file in autodetect mode, Windows-1252 is detected and "Ë" is shown.

Maybe there would be a good solution to check first if opened file's encoding matches user's ANSI / OEM code pages and only then guess other encodings?

Notepad++ v7.6.3   (64-bit)
Build time : Jan 27 2019 - 17:16:47
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll

**Comment by chcg** [comment]
@KJlt77 See #5414, so maybe with the upcoming 7.6.5 your problem is fixed. Anyhow the detection is just a heuristic/statistical approach and could therefore never be correct for all possible input.

**Comment by KJlt77** [comment]
@chcg Thanks. 7.6.5 solved the problem.
