### ISSUE TITLE
Inconsistent crash when dragging tabs

### ISSUE THREAD

**Issue by vtad4f** [notepad-plus-plus/notepad-plus-plus#4339]
### Description of the Issue
With several tabs open, when I drag them around notepad++ will occasionally crash. It happened 2-3 times one day and not again since. 

### Steps to Reproduce the Issue
1. Open a few tabs
2. Re-order the tabs by dragging-dropping

### Expected Behavior
Not crashing

### Actual Behavior
Crashing

### Debug Information
Notepad++ v7.5.6 (32-bit)
Build time : Mar 19 2018 - 00:26:59
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll PluginManager.dll

**Comment by MAPJe71** [comment]
Can not reproduce on Windows 10 64-bit with Notepad++ 7.5.6 32 bit or Notepad++ 7.5.6 64 bit.

**Comment by vtad4f** [comment]
Hi. Sorry for not providing this earlier. The info below is my current debug info. I saw this issue within the last two weeks, so it could also be 7.5.5 (32 bit).

Notepad++ v7.5.6   (32-bit)
Build time : Mar 19 2018 - 00:26:59
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll PluginManager.dll

**Comment by vtad4f** [comment]
I also frequently run with these cmd line options: **-multiInst -nosession**

**Comment by AngryGamer** [comment]
What kind of crash? Does notepad++ close itself? Does the Tab Bar freeze? Do you get an error message?

**Comment by vtad4f** [comment]
It wasn't just the tab bar that froze. I did not get an error message. Windows popped up the standard "Check online for a solution and re-open", "Close the program" options or something similar.

I haven't seen it since that day. It may have been an issue that was only present in 7.5.5.

**Comment by Pokechu22** [comment]
I can also reproduce this; it's happened 2 or 3 times (on separate days).  I did _not_ get a message from windows about the application crashing; it just hung for a few seconds and then closed.

I will note that when dragging the tab, the crash happens after the drag has stopped, and the file name in the dragged tab is blank.

I can't find any dumped crash report, but that may simply be because I don't know where to look for them.

**Comment by cmeriaux** [comment]
I have the same issue but I can't figure out what's going on. I can't find initial conditions to reproduce it.
I think we must have the "tab bar multi line" option activated. do you agree ?
We may also have a dependency with the file name length.
If someone can take a screenshot when the issue appeared ....
thanks

**Comment by Pokechu22** [comment]
I do have the tab bar multi line option active.  I don't think I had enough files open to have multiple lines in use at the time, though (and ample margin).

Next time it happens, I'll try to take a screenshot.

**Comment by cmeriaux** [comment]
Here is an example
![tabbar_crash](https://user-images.githubusercontent.com/12024941/41996635-ce6815ea-7a55-11e8-88e6-4235f2482888.png)

I'm trying to reproduce it with Npp compiled in debug mode with Visual Studio.
Something may be wrong in 'tab bar' object. Then when we close Npp, Npp can't destroy this object => deadlock

**Comment by Pokechu22** [comment]
I just reproduced this again; the tabs looked like this:

![npp_tabs](https://user-images.githubusercontent.com/8334194/45256568-060a6b80-b34d-11e8-8232-d254ed15a246.png)

The original tab list was this; I dragged the second build.gradle over and that's when it crashed.

![npp_tabs_orig](https://user-images.githubusercontent.com/8334194/45256575-1d495900-b34d-11e8-9084-2c012a2af80a.PNG)

Upon reopening, the drag went through just fine.

Unfortunately I failed to grab a crash dump or anything (I meant to force a memory dump from task manager but ran out of time before the program closed).

**Comment by Pokechu22** [comment]
Reproduced this a third time.  This time, I actually caught an issue beforehand: the tab list looked like this:

![npp_tabs_2](https://user-images.githubusercontent.com/8334194/46824532-f57f5380-cd45-11e8-94e3-1e8c1ae5a907.PNG)

where the last file was _actually_ named `1.12_fields.csv`, not blank.  I was able to safely edit and save the file, but notepad++ crashed it after I tried to move the tab.  However, in this case I noticed that it was blank beforehand and had the foresight to grab a memory dump beforehand.  I'm not sure exactly what information is in the dump, so I don't want to upload it right now, but I'll poke around with it and see if I can figure something out.

**Comment by cmeriaux** [comment]
@Pokechu22  The issue may be fixed thanks to c6e1a95098ada4db56dd9032bd5b2d4fa92458a7  a week ago.
Can you try again with the nightly build version  ( https://ci.appveyor.com/project/donho/notepad-plus-plus ) ?

**Comment by Pokechu22** [comment]
I don't have a consistent way of reproducing, unfortunately; I can update to the nightly build but I won't be able to say for sure that it is fixed (since I've only experienced it every month or so).

**Comment by clintr-at-kornak** [comment]
Hello, I see this or a similar problem on Windows 7 64-bit.  The difference is that the program seems to keep working until I try to close it.  Usually the dragged tab becomes blank.  I can still switch to my other tabs and edit in them, but when I try to close the program it hangs.  Have to kill it with task manager.  Then when I re-start it opens the tabs that were open the previous time I started it.
Also, if I try to drag a blank tab I get another blank tab.  Can't close any of the blank tabs, but I can close the others.
For me this seems to be happening a few times a week.  I run the program about 9 hours per day, 5 days a week.

**Comment by cmeriaux** [comment]
I'm also experiencing this issue. The bug is still here in the latest release

**Comment by Graham-G** [comment]
I've also experienced this issue, and can reproduce it consistently because I have a snapshot of the session in which it occurred. I can probably post that in a few days to help narrow down the issue if it's still present in the latest nightly.

**Comment by Pokechu22** [comment]
I just experienced this again using the 7.6.1 Dec 17 2018 13:23:44 development build, as a note.  I'm still not able to consistently reproduce it though; the session would be interesting to see.

**Comment by Pokechu22** [comment]
I encountered some weird behavior that I can vaguely say happens when the number of rows change and then you drag another tab (possibly it must be a different one from the current one, maybe not) where it appears to actually select a different tab than the one you clicked; I think this might be related.  I don't have time to investigate right now but I think that that might be a component that's required (perhaps the crash happens if the dragged tab is beyond the number of tabs or something).  This is only a guess and I'm just commenting so I don't forget.

Has anyone ever had this happen when multi-line for the tab bar is not enabled?

**Comment by balagansky** [comment]
This started happening to me at some point recently. I have multi-line enabled (also Reduce, Darken, Draw, Show).

The problem occurs consistently when I restore a session... unless the active tab is the leftmost tab. If the active tab is any other tab, then clicking on another tab causes weird behavior.

It seems to only happen when I have a certain number of tabs open, or a certain width of tabs. Seems to occur when total tab width percentage is at least 50% of the bar width. The least number of tabs I have reproduced this with is just 3.

I have even be able to induce this behavior without restarting by shrinking the window width.

**Comment by balagansky** [comment]
After debugging the source, I have determined that at least one of the symptoms I am seeing is caused by the TCM_SETCURFOCUS message in TabBar::activateAt when called during session load. Consistent with the observations in my previous post, this message is sent only when the starting tab is not the first tab (index == 0).

Not sending that message when activating a session seems to avoid the issues.

I posted a quick PR here: https://github.com/notepad-plus-plus/notepad-plus-plus/pull/6202

This PR is just a quick fix, not carefully tested.

**Comment by donho** [comment]
> This PR is just a quick fix, not carefully tested.

That means this PR is not really reliable.

**Comment by donho** [comment]
There are several iteration recently to enhance this issue. It should be fixed. 
Please reopen it if you have this issue in the latest version.

**Comment by balagansky** [comment]
I can still reproduce this issue. At the moment, reliably, but at other times I have not been able to repro it at all, so I'm not sure if there are some sort of external environmental factors as well. It appears to be sensitive at least in part to exactly which tabs are open and the window width.

Below is an animation of part (most) of the repro process running a local on master/HEAD. I've also reproduced this using the latest 7.7.1 release using the same steps. In at least one repro, the corrupted tabs had Chinese characters instead, and in most cases the tabs are blank.

![image](https://user-images.githubusercontent.com/56180447/67610675-324b9c00-f749-11e9-9314-c9b7afac30b0.png)

Circles in the gif represent mouse clicks

![npptabscorruption4_head](https://user-images.githubusercontent.com/56180447/67610685-3972aa00-f749-11e9-8edd-41abee1f2b60.gif)

Repro steps:
0. Enable multi-line tabs (close button on each tab setting is not necessary for repro - in the animation I have it enabled, but I can repro without it as well)
1. Open Notepad++ and load less than one full row of multiple tabs - window width might need to match roughly what mine is in the attached graphics.
2. Exit.
3. Open Notepad++, restoring the session
4. Close all tabs from left to right until none are left except a new document tab
5. Drag in all files in notepad++ exe directory except uninstall.exe (in my case I had an extra copy of the exe, but I can repro without that file as well just as easily)
6. Close tabs from right to left until readme.txt is the rightmost tab
7. Click on an inactive tab and move the mouse slightly
8. After another tab becomes corrupt, close any tab

**Comment by balagansky** [comment]
Removing these blocks of code seems to avoid the issue, but that alone may not be the right fix:

		// TCM_SETCURFOCUS is busted on WINE/ReactOS for single line (non-TCS_BUTTONS) tabs...
		// We need it on Windows for multi-line tabs or multiple tabs can appear pressed.
		if (::GetWindowLongPtr(_hSelf, GWL_STYLE) & TCS_BUTTONS)
		{
			::SendMessage(_hSelf, TCM_SETCURFOCUS, index, 0);
		}

**Comment by balagansky** [comment]
I think this issue is related to https://github.com/notepad-plus-plus/notepad-plus-plus/issues/6273

**Comment by balagansky** [comment]
Complete repro using only files from the 7.8 installer:

1. Open NPP, clear out all tabs, enable multi-line tabs, close
2. Open NPP, set window width to the same width as in the gif
3. Drag in all files from npp program folder as shown in gif
4. Close tabs until notepad++.exe is the last tab.
5. Close NPP
6. Launch NPP
7. Drag in all files from npp program folder as shown in gif
8. Close tabs until notepad++.exe is the last tab.
9. Click on inactive tab and drag slightly

![npptabcrash](https://user-images.githubusercontent.com/56180447/67640853-19162d00-f8ba-11e9-95ae-66dd79ce7fde.gif)

**Comment by Universal-Invariant** [comment]
Hate to bring this up but I've been having this problem recently(well, for at least the past year). Almost any time I move a tab the app crashes. Sometimes it doesn't do it when the program initially starts but basically I rarely move tabs around because of it. I'm using latest npp and this has happened across several recent versions. It started a while back. It is very likely due to some plugins. I have installed a lot. I think I went on an install spree about a year ago and then the problem started. I haven't really put any time to figure out which plugins it might be(as it's too time consuming).

There are a few plugins that may be the cause that I guess I can disable to see. Specifically I just removed MenuIcons as that seems to be the only plugin I have explicitly messing with tabs. So far it has been working but that isn't necessarily going to hold.

**Comment by pryrt** [comment]
@Universal-Invariant ,

> Specifically I just removed MenuIcons as that seems to be the only plugin I have explicitly messing with tabs. So far it has been working but that isn't necessarily going to hold.

MenuIcons is [known](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/14802#issuecomment-4749576019) to cause N++ to crash under similar circumstances to what you described. https://github.com/francostellari/NppPlugins/issues/71#issuecomment-4321741836 might provide a workaround that would enable you to try to re-install that plugin: from what I understand, the default "left hand side" option interferes with Notepad++'s newer pinning capabilities, which may be the root cause of the crash; users have reported that the other values for that option eliminates the crash.

**Comment by Universal-Invariant** [comment]
> [@Universal-Invariant](https://github.com/Universal-Invariant) ,
> 
> > Specifically I just removed MenuIcons as that seems to be the only plugin I have explicitly messing with tabs. So far it has been working but that isn't necessarily going to hold.
> 
> MenuIcons is [known](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/14802#issuecomment-4749576019) to cause N++ to crash under similar circumstances to what you described. [francostellari/NppPlugins#71 (comment)](https://github.com/francostellari/NppPlugins/issues/71#issuecomment-4321741836) might provide a workaround that would enable you to try to re-install that plugin: from what I understand, the default "left hand side" option interferes with Notepad++'s newer pinning capabilities, which may be the root cause of the crash; users have reported that the other values for that option eliminates the crash.

Thanks. I noted that a lot of times the * for saved files would appear for no reason so that is likely related. I changed the setting and still has issues I'll report back. Else it is working and that was the problem for me, at least.

**Comment by VinceKezel** [comment]
I've been having this same crash issue lately when dragging tabs. I do have Menu Icons 2.07 and Npp 8.9.6.4

I found this issue and it's comments via google

If I grab a tab from the third row and move to second row, then Npp instantly crashes/disappears with 100% reproducibility. Removing Menu Icons plugin is a complete fix --OR-- Menu Icons setting for the symbol on **right hand side** does seem to be a fix for me as well.

**Comment by Universal-Invariant** [comment]
> > [@Universal-Invariant](https://github.com/Universal-Invariant) ,
> > > Specifically I just removed MenuIcons as that seems to be the only plugin I have explicitly messing with tabs. So far it has been working but that isn't necessarily going to hold.
> > 
> > 
> > MenuIcons is [known](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/14802#issuecomment-4749576019) to cause N++ to crash under similar circumstances to what you described. [francostellari/NppPlugins#71 (comment)](https://github.com/francostellari/NppPlugins/issues/71#issuecomment-4321741836) might provide a workaround that would enable you to try to re-install that plugin: from what I understand, the default "left hand side" option interferes with Notepad++'s newer pinning capabilities, which may be the root cause of the crash; users have reported that the other values for that option eliminates the crash.
> 
> Thanks. I noted that a lot of times the * for saved files would appear for no reason so that is likely related. I changed the setting and still has issues I'll report back. Else it is working and that was the problem for me, at least.

I tried the solution and it mostly works but there are still crashes that happen when I move tabs, sometimes. It is much rarer. I think just twice in the last few weeks.
