### ISSUE TITLE
Incorrect collapsing of functions (multiple languages)

### ISSUE THREAD

**Issue by alex085** [notepad-plus-plus/notepad-plus-plus#4560]
STR:
1. Create new doc
2. Select "C" from "Language" menu
3. Type the code
```
void func1()
{
	//a {
	//}
	return;
}
```
"return" is not necessary. It is placed here to make the bug more visible.
4. Click menu "View->Fold All"

I expect folding like on picture 1.
![pic1](https://user-images.githubusercontent.com/18471286/41026422-32889b24-697d-11e8-9f68-c3151a572439.png)

Actually I get the case from picture 2.
![pic2](https://user-images.githubusercontent.com/18471286/41026440-3e431fd4-697d-11e8-9f0e-d8ea2b951dd6.png)

**Comment by abek42** [comment]
Similar issue with Javascript function folding.  Code example to replicate (place in an empty JS file) :
``````````
function brokenFold(arrHnd,callerFSId,fileFor){
	console.log("folding fails for this function");
	console.log("more something");
	//{thisCommentedLine: "breaks folding",removeTheLastCharacter:"on this line to fix folding" }	
	console.log("Do more something");
}

//this should be visible post fold

function dontHideMe(){
	console.log("I will be folded");
}

Notepad Version: 7.5.4 32-bit on Win10

**Comment by cgeroux** [comment]
This is bugging me also... if I put a space between the "//" and the "}" it works just fine. This seems like supper buggy behavior and inconsistent with other editors I have used which support code folding (e.g. MSVS). Is it possible to make that not the default setting on Notepad++ or to change it in the settings somewhere I haven't been able to find?

**Comment by bpersonick** [comment]
There are problems with all of the folding of all languages in the newer
versions of notepad++, not just in C, but in every language I have observed
very inconsistent behaviors.  For XML and VB I was able to reliably fix
folds by making sure there was always a full tab stop (or 4/5 spaces)
indent for all lines within a fold level, blank lines with no tabs/spaces
were the most common cause of the issue.

Those are built in languages like C, so it may apply to C as well.

In custom languages, the folding was not consistent with the vb/xml
findings.  I forget exactly what I had to do, but I did hit upon something
that fixed my folding issues 95% of the time by removing one of the other
formatting features I can check which later, but that is for custom langs,
and C is a built in lang.l, so try the tabbing

**Comment by zufuliu** [comment]
Isn't  XML/HTML folding based on start and end tag?

Scintilla's current folding for VB/VBS is based on indentation (like Python) not keyword. There are other implementations using keyword based folding.

**Comment by robotboy655** [comment]
Also having this problem on v7.5.9:
![image](https://user-images.githubusercontent.com/3299036/47609566-fdc7d600-da49-11e8-8fb0-4e5bb4e38310.png)

This also completely breaks all folding visualization on the left below the problematic ```//}``` which can lead you to believe that there's a syntax error somewhere above when there isn't one.

I can see how having this is useful:
```
//{ folding start
...
//} folding end
```
But the problem is that the closing comment ```//}``` works regardless if the opening comment ```//{``` exists or not, which is a bug.

If the root issue cannot be fixed, maybe we can have an option in NP++ to disable this broken feature?

**Comment by bugfreetech** [comment]
> 
> 
> This is bugging me also... if I put a space between the "//" and the "}" it works just fine. 

aaaaaaaaaaaaaaa this has driven me nuts for 5+ years and it's fixed with a space?!!! thanks! I had resorted to block comments :|

**Comment by Ekopalypse** [comment]
@alex085 npp 7.7 which uses a Scintilla 4.x version is available now, I assume this issue can be closed, right?

**Comment by zufuliu** [comment]
It not fixed, to fix this npp need to allow turn off explicit fold.
see https://github.com/notepad-plus-plus/notepad-plus-plus/issues/4560#issuecomment-410407042

**Comment by geeffland** [comment]
I think this is related to what I am seeing in a UDL.

When N++ places the fold end, it is off by the count of comment lines (rows).  If I go into the UDL editor and remove the characters that start a comment (so they aren't comments anymore) then the fold end appears in the correct location.  Note that this is with single line comments... I did not try multi-line comments

**Comment by Dean-NC** [comment]
JavaScript folding test:

```
function ab() {
	if (true) {
		if (next) {
			
		}
		//else {
		//}
	}
	else {
		
	}
}
```

The ab() function won't completely collapse for me. Version 7.8.2

**Comment by bugfreetech** [comment]
That's because you have //} in there.
It needs a space like // {

**Comment by Dean-NC** [comment]
I guess that's a limitation of npp or 1 of it's dependencies, since that's not required for correct JavaScript, right?

**Comment by bugfreetech** [comment]
Yeah, it's some technical bug that's not a bug, you just have to space all
commented curly end brackets // }

**Comment by Dean-NC** [comment]
@bugfreetech Thanks for letting me know!
