### ISSUE TITLE
Rectangular selection is not cleared if a new selection is created

### ISSUE THREAD

**Issue by Piet-Kannitverstan** [notepad-plus-plus/notepad-plus-plus#4570]
### Description of the Issue
If something is selected in a file, usually the selection is cleared when a new selection is created (except if control keys are pressed). 
**Issue:** If there exists a rectangular selection, this selection is NOT cleared if one (or more) lines are selected by clicking (and dragging) on the line numbers at the left side; the last line of the rectangular selection is unselected, the other lines remain selected.

In addition, if an "extended" cursor exists (CTRL+Click or ALT+Drag), only the last position of this extended cursor is cleared if entire lines are selected by clicking on the line numbers.

### Steps to Reproduce the Issue

1. Open a text file
2. Create a rectangular selection (ALT+Drag)
3. Click on a line number below your selection

### Expected Behavior

The rectangular selection is cleared (same behaviour as if a "normal" non-rectangular selection exists).
If an extended cursor exists, it "collapses", and the new cursor position is the begin of the new selection.

### Actual Behavior

The last line of the rectangular selection is cleared, the other lines remain selected.
If an extended cursor exists, the last position is cleared, and a new position is added at the begin of the new selection.

### Debug Information

Notepad++ v7.5.4   (32-bit)
Build time : Jan  1 2018 - 01:47:45
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : ActiveX.dll ComparePlugin.dll DSpellCheck.dll HexEditor.dll JSMinNPP.dll mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll NppTextFX.dll PluginManager.dll PythonScript.dll RunMe.dll SpellChecker.dll Tidy2.dll XMLTools.dll XPatherizerNPP.dll

**Comment by sasumner** [comment]
This is almost certainly a Scintilla problem, and if so it can't be solved by Notepad++ developers.  It needs to be reported to the Scintilla bug list and solved in that project.  Since Notepad++'s Scintilla isn't anywhere close to the current version, perhaps a simple updating would resolve the issue.

**Comment by Piet-Kannitverstan** [comment]
@sasumner: I checked the Scintilla bug report list and found that many bugs regarding rectangular selections have been solved about 8 years ago - but they are still present in Notepad++ 7.5.6 :-(

**Comment by sasumner** [comment]
@Piet-Kannitverstan 
I think it comes down to the N++ author has decided that updating Scintilla is not as important as other work...

**Comment by Ekopalypse** [comment]
@Piet-Kannitverstan npp 7.7 which uses a Scintilla 4.x version is available now, I assume this issue can be closed, right?

**Comment by dail8859** [comment]
Cannot reproduce this so I'm assuming the Scintilla upgrade fixed it.
