### ISSUE TITLE
Ever since I updated it takes forever to load big files

### ISSUE THREAD

**Issue by egoplant** [notepad-plus-plus/notepad-plus-plus#4951]
I have lot's of big list files I always have open in notepad++ that I use to search through. It has never been a problem before, they just sit open in a tab and I don't even notice them. However since I updated every time I open or close notepad++ it takes a full minute before I can interact with anything because it's loading the files in some way.

**Comment by donho** [comment]
Which type (in which language) of files they are?
Are they folded?

**Comment by MadSpaniard** [comment]
I'm also experiencing longer file load times for medium/large files with the new update 7.5.9 vs. the previous version 7.5.8.

I'm finding this almost across the board, but specifically on xml files (e.g. 500,000+ lines, 25mb total size) and txt files (60,000+ lines, 5mb total size).

Hopefully there's a simple/obvious solution for this, does anyone have any ideas?

**Comment by Myer** [comment]
Same here for me with 7.5.9.
I'm not sure which file(s) is the culprit since I have many tabs open by default. (I have the "Remember current session for next launch" option activated.)
Some have over 400k lines, most are only text without language highlighting.

For me 7.5.9 is completely unusable. After I start 7.5.9 I only see the menubar and the rest of the window is gray. I had Notepad++ open in this state the whole day now since I thought after a while it will process all the long files and let me close them but unfortunately that's not the case...

After I have downgraded to 7.5.8 it's usable again, Notepad++ starts with about two seconds waiting time.
I will close many tabs now and maybe try again with 7.5.9.

Debug Info (from 7.5.8 since I can't interact with 7.5.9 as mentioned):
```
Notepad++ v7.5.8   (32-bit)
Build time : Jul 23 2018 - 02:03:53
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : ComparePlugin.dll PluginManager.dll DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll
```

**Comment by egoplant** [comment]
Sorry for the late response. They are in no language, they are .txt files that are frequency word lists for languages. I ctrl+f them to see how common words are.

**Comment by 1652893647** [comment]
+1
7.5.9  too lang

**Comment by richard4339** [comment]
Assuming you haven't gotten past it (I didn't realize there were any releases post 7.5.9 since auto-update appears to be broken?), if you end process through task manager then reopen N++ it opens immediately. But once you close it that time and try to re-open, you have to go through the force close loop again.

**Comment by rolandh** [comment]
I also have extremely poor performance when opening 50mb txt files. Notepad goes not responding for about 20 seconds. I never remember this being an issue in the past.

This is breaking problem. I am looking for another text editor now as it is just unusable.

I have removed all config files and also removed plugins.

**Comment by richard4339** [comment]
I manually installed 7.6.3 this morning. The first launch after installing I had no issues. After a system reboot the lockup that forces me to force close N++ is still occurring.

**Comment by MetaChuh** [comment]
@richard4339 

if you have the DSpellCheck plugin installed:
can you please try to remove this plugin (or rename your DSpellCheck.dll temporarily to DSpellCheck.dl_), restart notepad++ and retry ?

reason: we had some reports about that, over at the notepad++ community, and removing the DSpellCheck plugin, resulted in a huge speedup when (re)opening a previous session with a lot of big files and many tabs.

**Comment by richard4339** [comment]
@metachuh I just uninstalled that plugin (I’ve used N++ for years and have never used it). I’ll report back if the “freeze” happens again now that it’s gone.

**Comment by rolandh** [comment]
Removing the DSpellCheck plugin has made a huge difference for us.

**Comment by MetaChuh** [comment]
@rolandh 

yes, 1-3 seconds for a tab switch between appx. 50mb files is about the usual speed on a 32 bit notepad++ 7.5.x

if you'd like to try out something faster:
* please download the latest portable notepad++ 7.6.3 x64 from here: https://notepad-plus-plus.org/repository/7.x/7.6.3/npp.7.6.3.bin.x64.zip
* extract npp.7.6.3.bin.x64.zip to your desktop or within your download folder.
* start notepad++ by double clicking on the notepad++.exe inside this npp.7.6.3.bin.x64 folder.
* open a few of your larger documents or logs.
* scroll all opened documents down a bit and set the cursor somewhere at the middle, instead of the top of the document.
* switch between all tabs and take track of the time between tab switches.

side notes:

this portable version can coexist with your current notepad++ installation and runs completely isolated from your installed version.
any settings or changes within the portable version, including installing or removing plugins using the built in "plugins admin" will not alter your installed version, and vice versa.

this portable 7.6.3 x64 should run considerably faster than your installed notepad++, even though it contains DSpellCheck by default. you will get another (albeit smaller) speed boost if you remove DSpellCheck from there too.

tab switching speeds will eventually decrease, if one or more of the larger documents are located on network drives or slower usb drives.

**Comment by rolandh** [comment]
@MetaChuh 

Using this version I loaded a 75mb and a 7mb txt, scrolled to the middle of each tab. Closed notepad, then opened it again and it takes 11 seconds to open. Once notepad is open changing tabs is instant with zero lag.

This is with a 12 core threadripper and a 1gigabyte/second nvme m2 ssd. Surely it shouldn't be this slow?

**Comment by sasumner** [comment]
> with a 12 core threadripper and ...

People always think these things surely must make a difference, but if the code itself isn't written with them in mind, well...

**Comment by richard4339** [comment]
Wow. Just wow. I'll admit I have WAY too many tabs open in N++, none (atm) are probably even approaching 100kb. With DSpellcheck disabled now, N++ opens up with my 100 or more tabs now in less than a second. I don't remember it opening this quickly with no tabs open.

**Comment by donho** [comment]
@MetaChuh I think it's time to remove DSpellCheck from the official release.
What do you think ?

**Comment by MetaChuh** [comment]
@donho 
yes, good idea.
everyone who needs DSpellCheck can always download it using plugins admin in the future.

i think it will be very easy to support, because a missing DSpellCheck will only be noticed after a completely fresh 7.6.4 install.

people who just upgrade from 7.6.3 to 7.6.4 will presumably not be affected, as they already have DSpellCheck inside their plugins folder. they can and will be supported as usual, if they experience a slowdown due to DSpellCheck.

**Comment by MetaChuh** [comment]
@rolandh 

> 
Once notepad is open changing tabs is instant with zero lag.

yes, and imho this is the only important thing.

i personally do not mind a 11 second startup time to open all tabs, as long as i can switch between tabs as instantly as possible, after everything has loaded up.
imho the current notepad++ x64 version 7.6.3. does a very good job at this, and i often have more than 5 multi-lines of tabs opened.

**Comment by Predelnik** [comment]
So first of all - I haven't seen this issue before and I'm sorry for it but it's really not easy to find all the relevant issues unless they are linked to me directly or separate DSpellCheck issues are created.

I'm not exactly aware how can DSpellCheck affect Notepad++ behavior to that extent. I've created the following test: 15 files each 400'000 - 20 symbol lines. And I confirm it really takes Notepad++ 7.5.9 around 10-12 cpu seconds to load and around 5-6 cpu seconds to switch to other tab, 3 cpu seconds to previously opened up tab. Personally I don't see much of a difference with or without DSpellCheck even with spell-checking turned on in these parameters even if there's 1 cpu second difference in initial load time, it's definitely not anything like 2x slowdown. So in this case it does not seem to be noticeable.

Also I checked that current github master version of N++ works much faster in cpu time and probably even faster in perceived time (I do not know what exactly was changed there), however still not see much of a difference with or without DSpellCheck present.

So I welcome the examples where difference with/without DSpellCheck is more clearly visible than in mine (Just write the specs I can do generation myself)

Also note that I'm testing on latest version of DSpellCheck where some things may have been imrpoved but if the spell-checking is turned off it should not really make much of a difference. https://github.com/Predelnik/DSpellCheck/releases/tag/v1.4.10

I have a theory where some of the time might be wasted but I have to profile Scintilla for that since how efficient certain Scintilla operations are is not always clear. I will try to do that shortly.

**Comment by MetaChuh** [comment]
@Predelnik 

thank you for your participation.

> So first of all - I haven't seen this issue before and I'm sorry for it but it's really not easy to find all the relevant issues unless they are linked to me directly or separate DSpellCheck issues are created.

all known incidents, back at the notepad++ community, that either had this lag problem or the "Exception reason: vector<T> too long" issue, were solved with satisfaction, once the o.p. uninstalled DSpellCheck.
(at least all cases, where we got feedback from the o.p., but i guess that even the 1-2 that did not report back, would have persisted, if their personal issue would not have been solved)

note: most of them were not even aware that they had DSpellCheck installed, as it is a forced, bundled plugin, so making DSpellCheck optional might be the most logical choice.

my best guess for the lack of reports at the DSpellCheck project site would be, that many users do not open an issue at the DSpellCheck project site, if they do not require a spell checker in notepad++.
all who do need DSpellCheck would probably have submitted an issue to your tracker already. (you would have to re-check that)

> however still not see much of a difference with or without DSpellCheck present.

yes, and thank god that it does not happen to all users, otherwise we would not get any sleep at all, assisting such hypothetically vast amount of reports ;-)

if you like, you can read more about every day incidents regarding DSpellCheck, or any other topics that might be of interest to you, over at the notepad++ community.
we would also appreciate, if you would take the time to answer some of them first-handedly.

**Comment by Predelnik** [comment]
> all known incidents, back at the notepad++ community, that either had this lag problem or the "Exception reason: vector too long" issue, were solved with satisfaction, once the o.p. uninstalled DSpellCheck.
> (at least all cases, where we got feedback from the o.p., but i guess that even the 1-2 that did not report back, would have persisted, if their personal issue would not have been solved)

Well that's just another problem - "Exception reason: vector too long" issue (which by the was way accidentally introduced while fixing performance problem) was fixed relatively fast in version 1.4.7. However Notepad++ still bundles version 1.4.6 (note: current version is 1.4.10) so I still get error reports for that.

> note: most of them were not even aware that they had DSpellCheck installed, as it is a forced, bundled plugin, so making DSpellCheck optional might be the most logical choice.

Well, considering previous point, if it will be better updated in this case, then maybe I agree. But for issues such as this I would still like to find out what is the problem how to reproduce it in my environment.

> my best guess for the lack of reports at the DSpellCheck project site would be, that many users do not open an issue at the DSpellCheck project site, if they do not require a spell checker in notepad++.

It does not have to be that at all, if removing DSpellCheck solves a problem anyone who maintains Notepad++ can send me a link and there were already cases like that in the past.

> all who do need DSpellCheck would probably have submitted an issue to your tracker already. (you would have to re-check that)

For issues of such nature it's unobvious, it's not always easy to guess that causes performance problems, no matter if you use or do not use plugin functionality.

> yes, and thank god that it does not happen to all users, otherwise we would not get any sleep at all, assisting such hypothetically vast amount of reports ;-)

So you are implying that it somehow depends on user's system configuration or hardware. Personally I fail to see how, if poor performance happens on weaker machine then larger files should make same issue appear on more performat machines or at least make plugin contribution noticeable. It may lie in the nature of the files used however that's why I'm asking for good examples.

> if you like, you can read more about every day incidents regarding DSpellCheck, or any other topics that might be of interest to you, over at the notepad++ community.
we would also appreciate, if you would take the time to answer some of them first-handedly.

https://notepad-plus-plus.org/community/topic/17212/an-exception-occured-due-to-plugin-dspellcheck-dll

Well so as I see you recommend updating DSpellCheck as a "workaround" but updating it in Notepad++ somehow is still not done. Version with a fix was released October 31 there were 4 Notepad++ versions since then.

**Comment by MetaChuh** [comment]
closed as plugin related.

removing dspellcheck resulted in a speedup for all participants of this issue, who experienced this slowdown and reported back.

**Comment by Predelnik** [comment]
Still got no example where I can reproduce speed-up with removing plugin of the newest version.

**Comment by MetaChuh** [comment]
@Predelnik 
yes, as your recent version works good.
this was an answer to the past as issue closing reason.
my apologies.

btw, now that you are here:
users see an empty language download list, if `show only recognised ones` is active.
for that i've made a noobie guide at the community:
https://notepad-plus-plus.org/community/topic/17416/spell-check/2

why does this happen and do you have an open issue for that ?

br

**Comment by Predelnik** [comment]
@MetaChuh 
No problem!

> btw, now that you are here:
> users see an empty language download list, if `show only recognised ones` is active.
> for that i've made a noobie guide at the community:
> https://notepad-plus-plus.org/community/topic/17416/spell-check/2
> 
> why does this happen and do you have an open issue for that ?

Unfortunately I did not get this reported on GitHub but it should be fixed in newest version
https://github.com/Predelnik/DSpellCheck/releases/tag/v1.4.12
Also I probably should have described fixes included in "Several fixes for download/remove dictionary dialogs." more in detail since some of them were more noticeable issues than others.

**Comment by MetaChuh** [comment]
@Predelnik 
ok, thanks.

if you don't get some issues at your tracker, it means that the notepad++ community support works as a good filter for your tracker. 👍

i will continue to support DSpellCheck at the notepad++ community, but we can not do that at the notepad++ issue tracker, due to its size. if a ticket can be closed by removing a plugin we have to do so, even if a newer version of a plugin does not produce that same issue.

many thanks for your help and best regards

**Comment by rolandh** [comment]
This problem is still reproduced for me with a standalone version of npp.7.8.2.bin.x64.7z

Scrolling a 75mb txt file causes 15-20 seconds of not responding. Once I've scrolled the entire file once the lag goes away.

**Comment by Predelnik** [comment]
@rolandh Is this related to spell-checker plugin or not? Because if not it might just be different issue.

**Comment by rolandh** [comment]
npp.7.8.2.bin.x64.7z does not include spell checker by default. It must be something else

**Comment by sasumner** [comment]
@rolandh I've perused your comments on this thread and I can't see that the file type of your large file(s) has been mentioned.  Can you tell us this?  To be clear, I think the extension on your file would do it.

**Comment by rolandh** [comment]
.c files exported from a decompiler (hence the size)

**Comment by sasumner** [comment]
>.c files

I wonder if the lexing of these files is what is making it slow?  How about changing the extension to `.txt` temporarily and then trying the file(s) and make a speed comparison?

**Comment by rolandh** [comment]
That fixed all my problems. However I really rely on the C style highlighting.

I don't mind the lexing being slow, but surely this could be offloaded to a worker thread in the background and do it in chunks. That way the main message loop is continually being pumped to keep the UI responsive.

Do you know if all this occurs in a worker thread currently? I'd be willing to help look into it if anyone can point me in the right direction.

**Comment by sasumner** [comment]
So the real problem (I think) is that the lexing is handled not by the Notepad++, but by the underlying editing component, which is governed by a separate project called Scintilla.

**Comment by rolandh** [comment]
Is there any reason that would run within the main UI thread and not be offloaded?

**Comment by rolandh** [comment]
@sasumner what would be the best approach to getting this problem solved? Even if scintilla is slow at doing this parsing, could we not offload this task to ensure the main UI thread is not locked?

Happy to help if possible I just do not know where to start in your code base as I am primarily a c# dev and not across the tooling required to effectively debug UI hangs in c++ programs.

**Comment by Predelnik** [comment]
@rolandh The first problem is that [scintilla](https://scintilla.org/) is entirely separate project which is used completely unchanged in Notepad++ so the changes has to be done on their side to support this. I have found some pretty old [discussion](https://groups.google.com/forum/#!msg/scintilla-interest/VFX2oG2olQo/Pen2Zx6DFCYJ) related to this kind of improvement but it doesn't look like much have changed from there. Anyway you can begin by posting on their [support forum](https://sourceforge.net/projects/scintilla/support)

**Comment by rolandh** [comment]
Does anyone have an alternative to notepad++ that I can use for large files? This issue is basically making the software unusable for me, having to rename all my files to .txt is a pain.
