### ISSUE TITLE
Line wrap : doesn't work

### ISSUE THREAD

**Issue by Kdmeizk** [notepad-plus-plus/notepad-plus-plus#517]
In tab "Preferences" -> "Editing" -> "Line Wrap" all options doesn't work. Nothing changes.

It seems this option in tab "Preferences" -> "MISC." -> "Auto-indent" overwrite these options of "Line Wrap" above because when checked or unchecked, changes are noticeable. But change "Line Wrap" options, with "Auto-indent" checked or not, changes nothing.

**Comment by donho** [comment]
This bug has been fixed in recent commit, the bug-fix will be in v6.8.1

**Comment by Kdmeizk** [comment]
It seems this bug didn't fix. Same problem or I don't look correctly. Could you check again please ? v6.8.2.
