### ISSUE TITLE
shortcut mapper not accessible to screen readers.

### ISSUE THREAD

**Issue by mltony** [notepad-plus-plus/notepad-plus-plus#6060]
### Description of the Issue
This is a copy of issue #429 - reopening as requested.
I was able to  reproduce it with the latest Notepad++.

### Steps to Reproduce the Issue
1. 
Open notepad++ with a screen reader such as nvda [nvaccess.org] and go to the settings menu with alt and arrow right to settings.
2. Activate the Shortcut mapper with nvda.
3. Press tab, and note that the list of keys isn't present, the only things present are close and one button called modify.
4. Press the insert key and numpad 7, (or if you are on a laptop keyboard, caps lock + page up) to activate screen review.
If you are on a laptop, press insert+n (numpad insert or extended insert).Now go to preferences and keyboard settings > laptop layout, and also while there, check the use caps-lock as an nvda modifier key check box.Press okay.
when I refer to the nvda key I mean (either one of caps-lock, insert, numpad insert.
Press nvda+numpad 7 or in laptop mode, nvda+pg up. It should say screen review.
5. Now use either numpad 9 to go down by line, or nvda+down arrow to go down by line in laptop mode.
If you do this correctly you should hear a number followed by an action.
These keys should be put into a list (similar to what we have with the windows list so that a screen reader can properly work with them. 

### Expected Behavior

The table of shortcuts in the shortcut mapper dialog window should be accessible with a screenreader.
### Actual Behavior

Screenreader doesn't recognize the table of shortcuts as a table, therefore it's impossible to interact with it, for example, it is impossible to change any shortcuts.

### Debug Information

Notepad++ v7.7.1   (64-bit)
Build time : Jun 16 2019 - 21:24:47
Path : c:\program files\notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppGTags.dll 

Please note, that I didn't try removing NppGTags plugin, as I am trying to set up shortcuts for that plugin, since it doesn't have any default shortcuts.

**Comment by Ekopalypse** [comment]
Not used any screen readers but it might be that the blocking nature of the shortcut dialog is
blocking the screen reader as well? Just a hint if someone is investigating this further.

**Comment by mltony** [comment]
I don't think so - screenreaders can typically work well with modal 
dialog windows.

I can access other elements of Settings Mapper window, such as tabs, 
buttons, filter edit box, just not the actual list of shurtcuts.

**Comment by Ekopalypse** [comment]
You are right, I've downloaded and executed NVDA, it sees shortcut mapper dialog and its tabs
but not its babygrid control, which is a non-standard windows control, maybe that's the source.
But enough guessing, hopefully some else with more knowledge in screen readers and npp jumps in
and is able to provide more useful information.

**Comment by adlevision** [comment]
Shame nobody is interested in fixing this.  Same issue as #429.  The plugin manager is also inaccessible, probably for the same reason. 
 Wish I could use this program effectively.

**Comment by mltony** [comment]
@adlevision
Please don't blame notepad++ maintainers. Notepad++ is a free and open source project and nobody is paid to do any work on it. And they don't owe you anything. 
I myself maintain   a couple of open-source projects and I know how annoying  it can be to receive accusatory comments like this one.

**Comment by adlevision** [comment]
No intent to be "accusatory."  I can't use the program effectively because I'm blind and it relies on custom controls in the places mentioned, and I wish someone would take on the issue.  If nobody is interested in taking it on, it's indeed a shame, as in "highly unfortunate," because it's a great program that I and others who are blind would love to use heavily.  Some blind people do, but they don't seem to need custom hotkeys or plugin management. 
 The previous issue posted about this was closed because the moderator said it was several versions old.  Well, nothing has changed.  My hope was that someone seeing what a long-standing issue it has been might be inspired to get interested.

**Comment by zahra21** [comment]
hello.
although i am not a professional user,
but i tested shortcut mapper with nvda now and confirm the list of shortcuts is not accessible for screen reader users.
the only sentence which i can read beside modify, clear, close, and filter button,
is this sentence.
No shortcut conflicts for this item.
i cant access the list of shortcuts at all.

**Comment by rimrul** [comment]
> Yes, nonstandard windows controls are not accessible out-of-the-box. Could this "babyGrid" control be replaced with a standard windows control that does the same thing? 

From what I can tell there is no standard datagrid control in the Win32 API, no.
We could theoretically switch to a different nonstandard grid control, but that would probably need similar work to add accessibility.

> Generally, standard windows controls are accessible with little to no modification by the author. As long as they are used properly, the screen reader should recognize them, and they should be keyboard operable.

We could theoretically put a bunch of labels, buttons and scrollbars into a grid-like layout, but I think something that a screen reader can actually recognize as one consecutive grid would be way better.

> THere are ways of making nonstandard controls accessible, but this is far more difficult then actually using a standard control.

NVDA does seem to support Microsoft UI Automation, so the easiest way to do that would probably be to write a [UI Automation provider](https://www.codemag.com/article/0810112/Writing-a-UI-Automation-Provider-for-a-Win32-based-Custom-Control). 
Babygrid could then be presented as [a DataGrid](https://docs.microsoft.com/en-us/windows/win32/winauto/uiauto-supportdatagridcontroltype) to NVDA and similar tools.

**Comment by Emil-18** [comment]
Hi.

I have created an NVDA add-on, (download link below), that, among other things, makes it possible to use the shortcut mapper with NVDA. It doesn't work out of the box yet. Here are the steps you have to go through to make it accessible. After downloading and installing the add-on:
* Open the shortcut mapper dialog, and press tab until NVDA reports "pane". You are now on the list with all the shortcuts.
* Press NVDA+alt+c, and choose "unknown" in the combo box you landed in, and press enter.
* You should now be able to navigate the list with the arrow keys.

The add-on will remember your choice, so you don't nead to do this every time you restart NVDA.

Download link: https://github.com/Emil-18/enhanced-control-support/releases/download/v1.0.1/enhancedControlSupport-1.0.1.nvda-addon

documentation: https://github.com/emil-18/enhanced-control-support

**Comment by Emil-18** [comment]
> NVDA does seem to support Microsoft UI Automation

@rimrul NVDA uses UIAutomation when the control has native support for it

**Comment by Hoang-Long2012** [comment]
This issue is still reproducible in Notepad++ 8.9.8 (64-bit) with NVDA.

The Shortcut Mapper command list is still not present in the keyboard tab order and cannot receive keyboard focus.

As a result, a screen reader user cannot browse the available commands using normal keyboard navigation. The **Filter** field is effectively the only practical way to locate a command when its name is not already known.

For example, to assign a shortcut to the `Function List` command, I have to enter `Function List` into the Filter field, locate the result, and then activate `Modify`.

NVDA's screen review can expose some of the text visually present in the dialog, but this does not provide an equivalent keyboard-accessible list that can be navigated and interacted with.

Tested with:

* Notepad++ 8.9.8 (64-bit)
* Windows 11 25H2
* NVDA

The issue therefore appears to still be present in the current version.

**Comment by Emil-18** [comment]
Hi. You can use the shortcut mapper with NVDA if you install the enhanced control support addon, and follow the steps I described above.Sendt fra min iPhone14. sep. 2026 kl. 14:21 skrev Hoàng Long ***@***.***>:﻿Hoang-Long2012 left a comment (notepad-plus-plus/notepad-plus-plus#6060)
This issue is still reproducible in Notepad++ 8.9.8 (64-bit) with NVDA.
The Shortcut Mapper command list is still not present in the keyboard tab order and cannot receive keyboard focus.
As a result, a screen reader user cannot browse the available commands using normal keyboard navigation. The Filter field is effectively the only practical way to locate a command when its name is not already known.
For example, to assign a shortcut to the Function List command, I have to enter Function List into the Filter field, locate the result, and then activate Modify.
NVDA's screen review can expose some of the text visually present in the dialog, but this does not provide an equivalent keyboard-accessible list that can be navigated and interacted with.
Tested with:

Notepad++ 8.9.8 (64-bit)
Windows 11 25H2
NVDA

The issue therefore appears to still be present in the current version.

**Comment by Hoang-Long2012** [comment]
Hello
@Emil-18
Thanks for the workaround.
I installed the Enhanced Control Support add-on and followed the steps you described.
It does improve keyboard interaction with the Shortcut Mapper: after setting the control to `unknown`, I can use the Up/Down arrow keys to move through the entries.
However, NVDA does not announce the currently focused entry when I move with the arrow keys.
If I press NVDA+Tab, NVDA reads the contents of the entire grid instead of the current data item.
So the add-on makes the grid keyboard-navigable, but NVDA still does not announce the individual item as focus moves.
This is still useful as a workaround, though, and it confirms that the underlying control can be interacted with from NVDA.

**Comment by adlevision** [comment]
I haven't tried the add-on in NPP, but I had it installed for awhile with an intent to test. It seemed to cause some stability or slow NVDA bootup behaviors, though the cause might have been elsewhere. I found a complete list of NPP shortcuts in the forums (sorry, don't have the link), so the filter box has been an ok workaround: I also manually edit and store a copy of the shortcuts.xml file afterwards.
I don't hold out hope for a native fix (no accessibility issues have ever to my knowledge been addressed by the dev community), but an NVDA user with C++ knowledge could run up an extension that'd do wonders: report markers, DSpell misspelling indicators, provide an accessible shortcut mapper, etc. You could even do some of it with the PythonScripts extension, but slowly.

**Comment by Emil-18** [comment]
Did you try the latest version? If not, you can download it from the ad on store. It should fix the arrow problemSendt fra min iPhone16. sep. 2026 kl. 12:41 skrev Hoàng Long ***@***.***>:﻿Hoang-Long2012 left a comment (notepad-plus-plus/notepad-plus-plus#6060)
Hello
@Emil-18
Thanks for the workaround.
I installed the Enhanced Control Support add-on and followed the steps you described.
It does improve keyboard interaction with the Shortcut Mapper: after setting the control to unknown, I can use the Up/Down arrow keys to move through the entries.
However, NVDA does not announce the currently focused entry when I move with the arrow keys.
If I press NVDA+Tab, NVDA reads the contents of the entire grid instead of the current data item.
So the add-on makes the grid keyboard-navigable, but NVDA still does not announce the individual item as focus moves.
This is still useful as a workaround, though, and it confirms that the underlying control can be interacted with from NVDA.

**Comment by Hoang-Long2012** [comment]
Yes, I tested the latest version from the NVDA Add-on Store. The arrow keys do work now, but NVDA still doesn't announce the focused entry when moving through the grid.

**Comment by Emil-18** [comment]
What do you mean by the arrow keys work, but it doesn’t read the focus? Doesn’t it read anything, or does it read something that is not the focus? Could you provide a debug log of what happens?Sendt fra min iPhone19. sep. 2026 kl. 01:46 skrev Hoàng Long ***@***.***>:﻿Hoang-Long2012 left a comment (notepad-plus-plus/notepad-plus-plus#6060)
Yes, I tested the latest version from the NVDA Add-on Store. The arrow keys do work now, but NVDA still doesn't announce the focused entry when moving through the grid.

**Comment by Hoang-Long2012** [comment]
Hi
@Emil-18,
Yes, I tested the latest version from the NVDA Add-on Store.
The arrow keys move the focus through the grid, but NVDA does not speak anything when I move between entries.
Here is the relevant output from NVDA's log viewer while the grid item is focused:
```text
name: 'Tên Phím tắt1Mới Ctrl+N T.2Mở... Ctrl+O T.3Mở thư mục chứa trong Explorer ... T.17'
role: DATAITEM
states: FOCUSABLE, FOCUSED
isFocusable: True
hasFocus: True
windowClassName: 'BABYGRID'
windowControlID: 2601
displayText: 'Tên Phím tắtCtrl+N T.Ctrl+O T.T.nd Prompt ...'
```
The interesting part is that NVDA reports the object as a `DATAITEM` and reports it as `FOCUSED`, so the focus itself appears to be exposed correctly.
However, the `name` and `displayText` contain the contents of the entire grid rather than the currently focused entry.
For example, the name starts with `Tên Phím tắt1Mới Ctrl+N...` and continues through many entries.
So my observation is:
1. The arrow keys do move through the grid.
2. NVDA recognizes the focused object as a `DATAITEM`.
3. `hasFocus` is `True`.
4. But the focused object's accessible name appears to represent the whole grid, not the individual entry.
5. Therefore NVDA has nothing useful to announce when the focus moves between individual entries.
If useful, I can also provide the full NVDA debug log around the arrow-key navigation.

**Comment by Emil-18** [comment]
I think I figured out what’s going on. The add-on looks at the text colors, and treats the text with the least occurring color as the area where the focus is located, almost like screen readers did back in the day. NVDA’s method for looking at the background color is a bit bugged, sometimes it works, other times it does not, and reports the wrong color. This is the case for the shortcut mapper, so it has to rely on the foreground color. In your case, it seems like the foreground color is equal across the whole control, maybe you have changed the color for some reason in the past? Could you open the shortcut mapper, arrow until you are sure you are on the first item, enter screen review, and check if the colors are equal on the selected item and on other items?Sendt fra min iPhone20. sep. 2026 kl. 14:58 skrev Hoàng Long ***@***.***>:﻿Hoang-Long2012 left a comment (notepad-plus-plus/notepad-plus-plus#6060)
Hi
@Emil-18,
Yes, I tested the latest version from the NVDA Add-on Store.
The arrow keys move the focus through the grid, but NVDA does not speak anything when I move between entries.
Here is the relevant output from NVDA's log viewer while the grid item is focused:
name: 'Tên Phím tắt1Mới Ctrl+N T.2Mở... Ctrl+O T.3Mở thư mục chứa trong Explorer ... T.17'
role: DATAITEM
states: FOCUSABLE, FOCUSED
isFocusable: True
hasFocus: True
windowClassName: 'BABYGRID'
windowControlID: 2601
displayText: 'Tên Phím tắtCtrl+N T.Ctrl+O T.T.nd Prompt ...'

The interesting part is that NVDA reports the object as a DATAITEM and reports it as FOCUSED, so the focus itself appears to be exposed correctly.
However, the name and displayText contain the contents of the entire grid rather than the currently focused entry.
For example, the name starts with Tên Phím tắt1Mới Ctrl+N... and continues through many entries.
So my observation is:

The arrow keys do move through the grid.
NVDA recognizes the focused object as a DATAITEM.
hasFocus is True.
But the focused object's accessible name appears to represent the whole grid, not the individual entry.
Therefore NVDA has nothing useful to announce when the focus moves between individual entries.
If useful, I can also provide the full NVDA debug log around the arrow-key navigation.

**Comment by Emil-18** [comment]
@Hoang-Long2012 When you have notepad ++ in dark mode, the add-on Won't work, as it is then unable to detect the color changes. I will try to fix this in the future at some point

**Comment by Hoang-Long2012** [comment]
I tested this in Light Mode as you suggested.
The add-on does work much better in Light Mode, and I can navigate the Shortcut Mapper grid with the arrow keys.
However, the speech output is still sometimes inconsistent.
For example, when moving between items, NVDA sometimes repeats the previous item, reads only a fragment of an item, or combines text from adjacent items.
Some examples from the Speech Viewer:
```text
Mới Ctrl+N T.
ới Ctrl+N T.2Mở... Ctrl+O T.3M
Mở thư mục chứa trong Explorer T.
r4Mở thư mục chứa trong Command P
Lưu như... Ctrl+Alt+S T.
.10Lưu như
```
The `data item` announcements are normal NVDA role announcements; the problem is the item text itself sometimes being detected incorrectly.
So it looks like Light Mode provides enough color information for the add-on to identify the focused area, but the color-based detection is still not always precise enough to isolate the current item.
Dark Mode, however, is much worse: the add-on cannot reliably detect the focus at all there.
Thanks for looking into this!

**Comment by Emil-18** [comment]
Nice. I know about the issue with speech becoming garbled, but I don’t know how to fix it. I think it happens because notepad plus plus draws one column at the time, instead of the whole row. It works fine in other applications. If you press NVDA plus tab after having moved the focus, the focused item should be announced correctly.Sendt fra min iPhone21. sep. 2026 kl. 14:36 skrev Hoàng Long ***@***.***>:﻿Hoang-Long2012 left a comment (notepad-plus-plus/notepad-plus-plus#6060)
I tested this in Light Mode as you suggested.
The add-on does work much better in Light Mode, and I can navigate the Shortcut Mapper grid with the arrow keys.
However, the speech output is still sometimes inconsistent.
For example, when moving between items, NVDA sometimes repeats the previous item, reads only a fragment of an item, or combines text from adjacent items.
Some examples from the Speech Viewer:
Mới Ctrl+N T.
ới Ctrl+N T.2Mở... Ctrl+O T.3M
Mở thư mục chứa trong Explorer T.
r4Mở thư mục chứa trong Command P
Lưu như... Ctrl+Alt+S T.
.10Lưu như

The data item announcements are normal NVDA role announcements; the problem is the item text itself sometimes being detected incorrectly.
So it looks like Light Mode provides enough color information for the add-on to identify the focused area, but the color-based detection is still not always precise enough to isolate the current item.
Dark Mode, however, is much worse: the add-on cannot reliably detect the focus at all there.
Thanks for looking into this!
