### ISSUE TITLE
PowerShell syntax highlighting fails to ignores backtick escape character in single-quoted strings

### ISSUE THREAD

**Issue by signalbox2** [notepad-plus-plus/notepad-plus-plus#6159]
### Description of the Issue
In current versions of PowerShell, everything inside a single-quoted string should be taken as a literal.  See PowerShell get-help about_quoting:

    Because the contents of single-quoted strings are
    interpreted literally, you cannot use the backtick character to
    force a literal character interpretation in a single-quoted string.

Notepad++ syntax highlighting treats a backtick within a single-quoted string as an escape character.  This is for version 7.7.1 64-bit.

### Steps to Reproduce the Issue
$a = 'text`'
$b = 'something else'

### Expected Behavior
The syntax highlighting should treat everything between single quotes as a literal string. The backtick should be ignored.

### Actual Behavior
The syntax highlighter starts a string with the first single quote of the first line, ignores the closing quote on that line and treats everything up to the opening quote of the next line as part of the string.  The pairing of single quotes is out of register for the rest of the file.

**Comment by ArkadiuszMichalski** [comment]
https://sourceforge.net/p/scintilla/bugs/2209/

**Comment by rdipardo** [comment]
Fixed in ScintillaOrg/lexilla@7758276

**Comment by iRon7** [comment]
This issue still exists for me.
Debug info:
```
Notepad++ v8.4.2   (64-bit)
Build time : May 29 2022 - 16:47:30
Path : C:\Program Files\WindowsApps\HaukeGtze.NotepadEditor_1.8420.1.0_x64__6bk20wvc8rfx2\notepad++.exe
Command Line : $COMMAND_LINE_PLACEHOLDER$
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 21H2
OS Build : 19044.2486
Current ANSI codepage : 1252
Plugins : 
    mimeTools (2.8)
    NppConverter (4.4)
    NppExport (0.4)
```
Am I doing something wrong or is the fix still not deployed?

**Comment by iRon7** [comment]
It appears that it still goes wrong if the *last* odd number of characters in the single quoted string are backticks, as in the given example:

```PowerShell
$a = 'text`'
$b = 'something else'
```

**Comment by ArkadiuszMichalski** [comment]
@iRon7
>Am I doing something wrong or is the fix still not deployed?

You should update Notepad++ to the latest version.

**Comment by iRon7** [comment]
Oops, I thought I just did but that was another system.
Thanks, it is resolved.
