### ISSUE TITLE
& (ampersand) character disappears in powershell script

### ISSUE THREAD

**Issue by bheinsius** [notepad-plus-plus/notepad-plus-plus#679]
when i edit file with extension ps1, ampersand characters disappear.

to reproduce:
1. open notepad++ 6.8.1
2. click New button for a new file
3. type ampersand character (&)
4. click save button and save file somewhere with name new1.ps1
5. see & character disappear.

**Comment by Blumenkind** [comment]
This happens at a .js file too! (Notepad 6.8, on Win 8.1)

**Comment by AntonyBaasan** [comment]
Hm, it OK (not happens) with Notepad 6.8.1, on Win 7. I'll try with Win 8.1.

**Comment by darkpumpkins** [comment]
( & ) character does not appear into cpp files too.

**Comment by bheinsius** [comment]
it happens on Windows 10 and Windows 7 for me

**Comment by h-h-h-h** [comment]
Reference: issue https://github.com/notepad-plus-plus/notepad-plus-plus/issues/729

**Comment by donho** [comment]
@bheinsius Please try v6.8.2 (the latest release). This issue is fixed in this version.

**Comment by bheinsius** [comment]
problem still exist for me in v6.8.2

On Wed, Sep 2, 2015 at 1:52 PM, Don HO <notifications@github.com> wrote:

> @bheinsius <https://github.com/bheinsius> Please try v6.8.2 (the latest
> release). This issue is fixed in this version.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/notepad-plus-plus/notepad-plus-plus/issues/679#issuecomment-137045911>
> .
>



-- 
Bart Heinsius
EOM -- Business Intelligence met visie en SAS
Splijtbakweg 117
1333 HJ Almere, The Netherlands
Tel.: +31 (0)85 - 877 8984
Mobiel: +31 (0)6 50 678 919
Internet: http://www.eom.nl
LinkedIn: http://nl.linkedin.com/in/bheinsius

**Comment by h-h-h-h** [comment]
Maybe the font setting and the font files were preserved during the update. Try to download the font Source Code Pro from its original download source in its latest version.

**Comment by bheinsius** [comment]
What is the font's "original download source in its latest version"?
I never downloaded any font as far as I'm aware.



Op 2 sep. 2015 om 14:29 heeft h-h-h-h <notifications@github.com> het
volgende geschreven:

Maybe the font setting and the font files were preserved during the update.
Try to download the font Source Code Pro from its original download source
in its latest version.

—
Reply to this email directly or view it on GitHub
<https://github.com/notepad-plus-plus/notepad-plus-plus/issues/679#issuecomment-137079227>
.

**Comment by h-h-h-h** [comment]
https://github.com/adobe-fonts/source-code-pro/releases/tag/2.010R-ro/1.030R-it

**Comment by bheinsius** [comment]
sorry i'm just a notepad++ user i don't know what i should do with source
code for fonts.

i uninstalled notepad++ v6.8.2
i reinstalled notepad++ v6.8.2 (run as administrator)
now i see default font is courier and ampersand is no longer missing.
i then changed global font to source code pro and see ampersands is still
missing.

On Wed, Sep 2, 2015 at 8:42 PM, h-h-h-h <notifications@github.com> wrote:

>
> https://github.com/adobe-fonts/source-code-pro/releases/tag/2.010R-ro/1.030R-it
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/notepad-plus-plus/notepad-plus-plus/issues/679#issuecomment-137204947>
> .
>



-- 
Bart Heinsius
EOM -- Business Intelligence met visie en SAS
Splijtbakweg 117
1333 HJ Almere, The Netherlands
Tel.: +31 (0)85 - 877 8984
Mobiel: +31 (0)6 50 678 919
Internet: http://www.eom.nl
LinkedIn: http://nl.linkedin.com/in/bheinsius

**Comment by h-h-h-h** [comment]
By "Source code" they mean the font name. Call it misspelled. The download contains TTF files! Other font files may be in the Notepad++ directory. I would delete them to not supersede the downloaded ones.

**Comment by bheinsius** [comment]
ok deleted source code pro fonts through windows settings (Control
Panel\Appearance and Personalization\Fonts)
then installed new ttf files from
https://github.com/adobe-fonts/source-code-pro/releases/tag/2.010R-ro/1.030R-it
then set global font to source code pro in notepad++ style configurator
then set "Enable global font" option in notepad++ style configurator
now ampersand character no longer disappears.
thanks.

On Wed, Sep 2, 2015 at 9:25 PM, h-h-h-h <notifications@github.com> wrote:

> By "Source code" they mean the font name. Call it misspelled. The download
> contains TTF files! Other font files may be in the Notepad++ directory. I
> would delete them to not supersede the downloaded ones.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/notepad-plus-plus/notepad-plus-plus/issues/679#issuecomment-137220351>
> .
>



-- 
Bart Heinsius
EOM -- Business Intelligence met visie en SAS
Splijtbakweg 117
1333 HJ Almere, The Netherlands
Tel.: +31 (0)85 - 877 8984
Mobiel: +31 (0)6 50 678 919
Internet: http://www.eom.nl
LinkedIn: http://nl.linkedin.com/in/bheinsius

**Comment by h-h-h-h** [comment]
Fine!
