### ISSUE TITLE
Resizing panes allows automatic resizing of Other View

### ISSUE THREAD

**Issue by andrewlvaldez** [notepad-plus-plus/notepad-plus-plus#680]
Open the Other View along with the search results pane. 

Resize the height of the results pane then mouse over the splitter between Views left to right. 
The Views resize without actually clicking on the splitter.

This happens when you resize any of the other panes, ie document map, functions list, search results.

Using v6.7.9 on Windows 7.

**Comment by Rikk** [comment]
I think this is already fixed in 6.8.1.
As a tip, always test with latest version before reporting issues. :smirk:

**Comment by andrewlvaldez** [comment]
Very valid point, but unfortunately it's still broken v6.8.1 :smirk:

**Comment by Rikk** [comment]
ooops you're actually correct, I could reproduce now.

**Comment by donho** [comment]
I believe this issue has been fixed since long time ago.
Update your Notepad++ to the latest version (v7.6.6).
If the issue persists, please create a new issue for it.
Thank you.

**Comment by SinghRajenM** [comment]
@donho Nope, this is not yet fixed. A PR #5554 has been submitted

**Comment by MetaChuh** [comment]
@SinghRajenM 
@SinghRajenM 
we will leave this closed as less detailed predecessor duplicate of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/5516

many thanks for your fixes and tracking down each duplicate, much appreciated.
