### ISSUE TITLE
Download-Links do not work

### ISSUE THREAD

**Issue by tchara** [notepad-plus-plus/notepad-plus-plus#7611]
### Description of the Issue

All download links on the new website don’t work.
Addiditonally, there is no place to create an issue for the website (e-mail address is for praise and worship only).

### Steps to Reproduce the Issue

1. Go to https://notepad-plus-plus.org/downloads/
2. Select an version
3. Try downloading any of the installers, archives, ...

### Expected Behavior

An http(s) download of the installer, archive, ... should start.

### Actual Behavior

Nothing. Mostly a timeout occurs. Sometimes, HTTP 404. Seldomly, HTTP 200 with Debian’s “It works” default website.

### Debug Information

There is no debug information under “?” in my browser.

**Comment by the-j0k3r** [comment]
Also updates do not work, The updater pops up says theres an update, then after telling it to update, it dies saying it cant connect.

Also burned my retinas while visiting the new site all WHITE.

**Comment by wolf99** [comment]
Also seeing this issue.

@the-j0k3r try Dark Reader extension if using Chrome or Firefox browsers (https://chrome.google.com/webstore/detail/dark-reader/eimadpbcbfnmbkopoojfekhnkhdbieeh)

**Comment by the-j0k3r** [comment]
I use stylus and I dont use Chrome. Old site was dark new site is eye gauging white.

**Comment by tchara** [comment]
Or, you could just scroll down and activate the dark theme. There is a button at the end of the site.

**Comment by chojrak11** [comment]
Hey guys please publish Notepad++ binaries on GitHub like every other project.

**Comment by Ekopalypse** [comment]
Download seems to work for me, tried 7.8.1 x64 installer and zip, both worked.

![image](https://user-images.githubusercontent.com/47723516/69149978-91de6280-0acf-11ea-8153-624ec0871443.png)

**Comment by the-j0k3r** [comment]
> Or, you could just scroll down and activate the dark theme. There is a button at the end of the site.

Well should be default but with a non purple icon, at least apply a hue-rotate to that filter and throw some contrast to fine tune.

I have a feeling we all gone offtopic though. odd.

**Comment by tchara** [comment]
> Download seems to work for me, tried 7.8.1 x64 installer and zip, both worked.
> 
> ![image](https://user-images.githubusercontent.com/47723516/69149978-91de6280-0acf-11ea-8153-624ec0871443.png)

I can confirm it partially. One of my machines in Russia could download the 32-Bit installer without problems. However, another machine in Germany still just gets an http timeout.

**Comment by aeroncastle** [comment]
not working for me too, I'm from Brazil. You guys should have the installers on github too and not only the source code

**Comment by Ekopalypse** [comment]
Something strange here.
I can download from Germany using firefox and chrome but NOT using brave browser.

**Comment by the-j0k3r** [comment]
Updater finally worked, very slowly, took some 30 seconds ++, clearly some serving issues.

Is there a new service in place? [Read somewhere ](https://www.ghacks.net/2019/10/11/notepad-7-8-update-released-after-server-incident/) there were some service issues.

**Comment by the-j0k3r** [comment]
@tchara https://github.com/notepad-plus-plus/notepad-plus-plus/issues/7621 enjoy

**Comment by gizmecano** [comment]
As @the-j0k3r wrote :

> Also updates do not work, The updater pops up says theres an update, then after telling it to update, it dies saying it cant connect.

I'm not sure this issue is _absolutely_ related with the main title of the present thread (_Download-Links do not work_), but I can confirm that the updater still not works right now (a `curl error` is reported as title of the error box):

![npp-curl-error-timed-out](https://user-images.githubusercontent.com/852661/69320904-59ab6100-0c42-11ea-9dfd-d739a062118f.jpg)

**Comment by the-j0k3r** [comment]
Its either server or routing issue very likely. The random results in diff countries and even my own experience of trying it later and works albeit slowly to respond so indicates.

**Comment by gizmecano** [comment]
> Its somewhat related to download links not working, the two issues are likely linked.

This is also my opinion, although, as I wrote, I have no certainty.

In addition, it is this uncertainty that just explains why I preferred to add a comment on this issue dedicated to _download links_ rather than to open a new issue specifically devoted to the updater.

**Comment by donho** [comment]
This issue should be solved since yesterday.
Could you guys check it again?

**Comment by Ekopalypse** [comment]
Manual downloading using Firefox, Chrome, and Brave browsers worked for me.

**Comment by kcollins7** [comment]
Just had some issues for awhile trying to manually download but then it worked all of a sudden and still getting update timeouts.

**Comment by chojrak11** [comment]
Not much has changed, still timeouts and problems downloading.

I saw no comment on my idea to publish binaries as assets on GitHub. You published 171 releases on GitHub in releases page, but there are only source archive files. The binaries are only on your site.

The idea is - keep the binaries on your site if you wish, but additionally publish them on GitHub in assets just like almost every project on GitHub does.

**Comment by wolf99** [comment]
Still failing for me from within the application and at the web location.
(Seeing as location seems to make a difference according to earlier comments: I can say I am based in western Europe)

**Comment by the-j0k3r** [comment]
If this is dns related it will take a bit unless it was refreshed

**Comment by tchara** [comment]
Still dead for me in Germany and the Netherlands. Russia and USA work.

**Comment by WithoutPants** [comment]
The downloads page (https://notepad-plus-plus.org/downloads/) now returns a 404.

**Comment by elsamuko** [comment]
Completely down now:
https://downforeveryoneorjustme.com/download.notepad-plus-plus.org
> It's not just you! download.notepad-plus-plus.org is down.

**Comment by Neurotoxin001** [comment]
ERR_NAME_NOT_RESOLVED now.

**Comment by tchara** [comment]
Seems to be resolved for now. Works from my locations.
