### ISSUE TITLE
Can not enter number of characters for autocomplete setting

### ISSUE THREAD

**Issue by GwenDragon** [notepad-plus-plus/notepad-plus-plus#8443]
### Description of the Issue

If you have set in your Windows settings the Scaling to 125% to and want to change in Notepad++'s Preferences → Auto-Completion the number of characters, nothing can be entered.

### Steps to Reproduce the Issue

1. Open Windows settings → Display Scaling and set to to 125%
2. Open Notepad++ Settings → Preferences → Auto-Completion
3. Click on number in 'From 1 th character'
4. Enter 2 or 3
5. No number is shown
6. Setting can not be done

### Expected Behavior

Number can be entered 

### Actual Behavior

Number can not be entered 

### Debug Information

Notepad++ v7.8.7   (32-bit)
Build time : Jun  5 2020 - 02:34:28
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2004
OS Build : 19041.329
Current ANSI codepage : 1252
Plugins : ComparePlugin.dll Explorer.dll HTMLTag_unicode.dll JSLintNpp.dll JSMinNPP.dll LanguageHelp.dll mimeTools.dll NppConverter.dll NppExec.dll NppExport.dll NppFTP.dll NppRegEx.dll NppTextFX.dll RunMe.dll Tidy2.dll XMLTools.dll

**Comment by sasumner** [comment]
@GwenDragon How about providing a screenshot?

Here's what mine looks like (seems to be OK):

![image](https://user-images.githubusercontent.com/30118311/85201564-8013a680-b2ce-11ea-85f8-02f6ed80d841.png)

Notepad++ v7.8.7   (32-bit)
Build time : Jun  5 2020 - 02:34:28
Path : C:\\.................\npp.7.8.7.bin\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1809
OS Build : 17763.1039                      <------------------ **_this is different between us_**
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by GwenDragon** [comment]
1. Open Windows Display settings and set Scaling to 125%
2. Start Notepad++
3. Open menu Settings → Preferences
4. Select Auto-Completion
5. Click on the number to change it
6. Number is marked automatically 
7. Hit key 2 (on regular keyboard) 
8. Number is not seen and error sound is audible! See GIF animation

![error-sound-eneter-number](https://user-images.githubusercontent.com/46133149/85202868-f41f7000-b309-11ea-8454-da5d35ada425.gif)

**Comment by vertigo220** [comment]
[Pretty common problem for years, and still exists](https://community.notepad-plus-plus.org/topic/12458/can-t-change-autocomplete-from-1-th-character/9)

**Comment by donho** [comment]
@GwenDragon I cannot reproduce this issue at all.
Could you remove all plugins and test it again?

**Comment by sasumner** [comment]
@donho My recollection is that @Uhf7 solved this issue by altering a setting in the project file:  https://github.com/notepad-plus-plus/notepad-plus-plus/commit/e2a650ec1054610267ee49b0dea0b0c458bc19ad#diff-7fb45196ee8f346074097ee047fff7b8e3b6c5a01d88adea0c55ef1cb2d7a039

**Comment by donho** [comment]
@sasumner  
OK. So this issue has been solved. Thank you.

@GwenDragon 
Please use the latest version in which this issue has been solved.

**Comment by GwenDragon** [comment]
> @GwenDragon I cannot reproduce this issue at all.
> Could you remove all plugins and test it again?

I removed all Plugins and retried. 
Bug is still existing with Notepad++ 7.9.2.

**Comment by donho** [comment]
@GwenDragon 

OK, thank you for your retest.
I'll reopen this bug - but we cannot fix it if we cannot reproduce it.

Could you provide your 7.9.2 debug info please?

**Comment by GwenDragon** [comment]
> Could you provide your 7.9.2 debug info please?

`Notepad++ v7.9.2   (32-bit)
Build time : Dec 31 2020 - 03:58:36
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2009
OS Build : 19042.746
Current ANSI codepage : 1252
Plugins : ComparePlugin.dll Explorer.dll JSLintNpp.dll JSMinNPP.dll LanguageHelp.dll mimeTools.dll NppConverter.dll NppExec.dll NppExport.dll NppFTP.dll NppTextFX.dll RegexTrainer.dll RunMe.dll Tidy2.dll XMLTools.dll 
`

**Comment by GwenDragon** [comment]
I had standard scaling settings in Windows Settings → Display.
The i tested this:
Windows Settings → Display
Change size of text, apps ...
Set to 125%
Select Advanced Scaling Settings
Set "Let Windows try to fix apps so they are not blurry" to OFF
Start Notepad++
Open settings for Autocomplete
Click on the number to change
Popup opens
Now the number field accepts a number!

Windows issue or Notepad++ issue?

**Comment by Uhf7** [comment]
I could reproduce this as follows:
- Close Notepad++
- Set display scaling to from 100% to 125%
- Sign off and sign on again (only now after this the dialogs will use the new fonts)
- Start Notepad++

**Comment by vertigo220** [comment]
So literally the day after I mentioned that the issue still exists, it was closed saying it's not broken...

**Comment by sasumner** [comment]
>So literally the day after I mentioned that the issue still exists, it was closed saying it's not broken...

I guess you missed the "reopening" and then the "fixing", before final closure.
With the closure, we hope it is fixed, but you won't know until the next release, unless you want to try an intermediate build that contains the fix.

**Comment by vertigo220** [comment]
I didn't miss it. My point is it should never have been closed in the first place, since I had _just_ mentioned the issue was still there, thereby requiring it to be reopened when it was pointed out by someone else that, surprise, it was still there and so the issue shouldn't be closed. Even if it was suspected as fixed, closing it without confirmation would be premature. Doing things like this gives the message that dealing with issues isn't important, closing them is, and discourages people from contributing by reporting issues and helping troubleshoot.

**Comment by sasumner** [comment]
>it should never have been closed in the first place

Accidents (and misunderstandings) happen.  
Reopening is "inexpensive".

In the future, try to improve your own comments on this issues list, to wit:

* Try to avoid comments like "still there" -- it isn't real helpful. Cite a version that it is "still there" in. If you are agreeing with the OP's reported version number that a bug is in; say so.

* You post your comment text as a link to some ancient Community posting, without any explanation of what's relevant there.  I suspect it has absolutely nothing to do with the real bug of this issue, but rather the bug that was fixed by the recent change by Uhf7 that I cited.

>...and discourages people from contributing by reporting issues and helping troubleshoot

Well if you are going to help troubleshoot, we look forward to your reporting on the status of the fix to this issue before it is released in the next version.

**Comment by Uhf7** [comment]
@vertigo220 

The .exe file to test would be
https://ci.appveyor.com/api/buildjobs/k46tydyearlrddpp/artifacts/Notepad%2B%2B.Win32.Unicode%20Release.exe

It should be copied into the directory where `Notepad++.exe` (7.9.2 32 bit) already is. Then, `Notepad++.exe` and `Notepad++.Win32.Unicode Release.exe` can be started alternatively. The bug should occur with the original `Notepad++.exe`, and should be gone with the new `Notepad++.Win32.Unicode Release.exe`.

Please save all your files before testing, and don't run both .exe files at the same time.
