### ISSUE TITLE
Preferences Dialog: UI controls for "Line number margin width constant/dynamic" don't reflect state of this setting set via NPPM_SETLINENUMBERWIDTHMODE

### ISSUE THREAD

**Issue by dinkumoil** [notepad-plus-plus/notepad-plus-plus#9344]
### Description of the Issue
In Preferences dialog, the UI controls for "Set line numbers margin width constant/dynamic" don't reflect the state of this setting if it has been set via `NPPM_SETLINENUMBERWIDTHMODE` message.

### Steps to Reproduce the Issue
1. Replace `notepad++.exe` from your regular v7.9.2 installation with the one from AppVeyor artifact that includes the fix for #9338 ([see here](https://ci.appveyor.com/project/donho/notepad-plus-plus/builds/37081175)).
2. Open Notepad++  and Install `NppExec` plugin.
3. After restart, go to `(menu) Settings -> Preferences -> Margins/Border/Edge -> Line Number`. Tick checkbox `Display` and radio button `Dynamic width`.
4. Open a file with more than 1000 lines.
5. Open `NppExec` plugin's console and execute the following command: `npp_sendmsg 2123 0 1`. This sets line numbers margin to constant width. You will observe that its width will increase because the file opened in step 3 has more than 1000 lines which needs a line numbers margin fitting 4 digits whereas its default width fits only 3 digits.
6. Go to `(menu) Settings -> Preferences -> Margins/Border/Edge -> Line Number`. The UI controls still show `Dynamic width`.

### Expected Behavior
The UI controls under `(menu) Settings -> Preferences -> Margins/Border/Edge -> Line Number` should reflect the current state of that setting.

### Actual Behavior
The UI controls under `(menu) Settings -> Preferences -> Margins/Border/Edge -> Line Number` reflect the state of that setting according to the content of file `config.xml`.

### Debug Information
Notepad++ v7.9.2   (32-bit)
Build time : Jan  3 2021 - 01:05:48
Path : E:\Desktop\Notepad++ Portable\npp.7.9.2.bin.x86\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1909
OS Build : 18363.1256
Current ANSI codepage : 1252
Plugins : AutoCodepage.dll BracketsCheck.dll ComparePlugin.dll Explorer.dll ExtSettings.dll LuaScript.dll MIMETools.dll NppConverter.dll NppEventExec.dll NppExec.dll NppExport.dll NppFTP.dll NppHorizontalRuler.dll NppMarkdownPanel.dll NppSaveAsAdmin.dll NppTextFX.dll NppToolBucket.dll NppUISpy.dll Pork2Sausage.dll ReloadFile.dll XMLTools.dll _CustomizeToolbar.dll

**Comment by donho** [comment]
Fixed by https://github.com/notepad-plus-plus/notepad-plus-plus/commit/aca736b766ee8781b9ea9e2cbf56ee92c2b1abd8

**Comment by dinkumoil** [comment]
**This** issue here is **not fixed**! Please re-read my posting above. I used the AppVeyor artifact that includes [aca736b](https://github.com/notepad-plus-plus/notepad-plus-plus/commit/aca736b766ee8781b9ea9e2cbf56ee92c2b1abd8) for testing and found the bug I elaborated above. 

**This issue should be reopened!**
