### ISSUE TITLE
Search textarea: `Ctrl`+`Backspace` does not delete, but adds a character, and `\` and `/` are not word separators.

### ISSUE THREAD

**Issue by sapioit** [notepad-plus-plus/notepad-plus-plus#9671]
### Steps to Reproduce the Issue

1. Press Ctrl+F to open the Find window
2. Write some text
3. Press `Ctrl`+`Backspace`
4. Notice that instead of deleting the last word, the character `` (ascii 127, hexa 7F) is added.
[Apparently](https://superuser.com/questions/332026/notepad-ctrl-backspace-behavior), this happens because the textarea in cause doesn't have autocomplete enabled.
5. If you have something which includes slashes (forwardslashes) and backslashes, you will see that neither is seen as a word separator. The character `/` is not seen as a word separator, and `\` is not seen as a word separator. 

### Expected Behavior
- `Ctrl`+`Backspace` should delete the last word (characters from where the input cursor is, to after the previous word separator).
- `/` should be seen as a word separator (like space is), and `\` should be seen as a word separator.

### Actual Behavior
- `` (ascii 127, hexa 7F) is added.
- `/` is treated as part of the word, and `\` is treated as part of the word.

### Debug Information
Notepad++ v7.8.6   (32-bit)
Build time : Apr 21 2020 - 15:17:06
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS Name : Windows 7 Ultimate (64-bit) 
OS Build : 7601.0
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by mere-human** [comment]
Have you tried on a more recent version (the latest is 7.9.4)? You can use portable version just for the test.

**Comment by sasumner** [comment]
This was fixed in https://github.com/notepad-plus-plus/notepad-plus-plus/commit/fb5c30002fd0c027b6d1b74a2d27adfded8011ee and is present in Notepad++ 7.8.8 and later versions.

**Comment by sasumner** [comment]
>If you have something which includes slashes (forwardslashes) and backslashes, you will see that neither is seen as a word separator. The character / is not seen as a word separator, and \\ is not seen as a word separator.

>/ should be seen as a word separator (like space is), and \\ should be seen as a word separator.

So this is a separate thing, for which you should have created a separate issue, but since I don't understand what you mean, we can treat it here for now.  Please give a concrete example showing why this is a problem for you.

**Comment by sapioit** [comment]
In a newer version, the `Ctrl`+`Backspace` works, but the `/` and `\` are still not seen asseparators. 

_Thanks for reminding me I didn't update `Notepad++`! I didn't notice that._

### Debug Information
Notepad++ v7.9.4   (32-bit)
Build time : Mar 15 2021 - 01:00:14
Path : V:\Programs\Notepad++Portable\App\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : ON
OS Name : Windows 7 Ultimate (64-bit) 
OS Build : 7601.0
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by sapioit** [comment]
> > If you have something which includes slashes (forwardslashes) and backslashes, you will see that neither is seen as a word separator. The character / is not seen as a word separator, and \ is not seen as a word separator.
> 
> > / should be seen as a word separator (like space is), and \ should be seen as a word separator.
> 
> So this is a separate thing, for which you should have created a separate issue, but since I don't understand what you mean, we can treat it here for now. Please give a concrete example showing why this is a problem for you.

## Case 1:

### Steps to Reproduce the Issue

1. Press Ctrl+F to open the Find window.
2. Write `a\b` (random characters).
3. Press `Shift`+`Left`.

### Expected Behavior
4. `It selects selects `b`.

### Actual Behavior
4. `It selects selects `a\b`.

## Case 2:

### Steps to Reproduce the Issue

1. Press Ctrl+F to open the Find window.
2. Write `a/b` (random characters).
3. Press `Shift`+`Left`.

### Expected Behavior
4. `It selects selects `b`.

### Actual Behavior
4. `It selects selects `a/b`.

**Comment by sasumner** [comment]
I understand now.  Thank you for the clarification.
However, when I try it, I get the "Expected behavior" for Case 1 and Case 2.
So I'll have to say "can't reproduce".

**Comment by sapioit** [comment]
> I understand now. Thank you for the clarification.
> However, when I try it, I get the "Expected behavior" for Case 1 and Case 2.
> So I'll have to say "can't reproduce".

I checked it again, and now `\` is kind-of seen as a word separator, meaning that `shift`+`left` selects the word, but includes the `\` in the word. I'll open a new issue.
